### ISSUE TITLE
Levels resetting

### ISSUE THREAD

**Issue by Dev-Mug** [Globox1997/LevelZ#10]
This mod is in use in the minecraft medieval [Fabric] pack on Curse forge. Server and clients are running 1.0.1 of your mod. Me and a friend noticed that our brewing levels reset randomly back to 0. The server does restarts every 6 hours. No other mods have been added to the pack by us. Not sure what would have caused that or if there is a fix/way to add them back other than spawning/giving xp. Just wanted to make you aware of the issue. Thanks!

**Comment by Globox1997** [comment]
Does this modpack use the latest version of the levelz mod?
