### ISSUE TITLE
[1.18.1] Shift + right clicking an ingredient in the brewing stand results in a crash

### ISSUE THREAD

**Issue by MarkNoName** [Globox1997/LevelZ#100]
+ Crash Log

https://pastebin.com/MBXUE8ve

+ Also, some of the ingredients get double the restrictions shown up

![Screenshot 2022-01-24 181539](https://user-images.githubusercontent.com/35975662/150831773-1bdf8f64-ff3e-47f4-bc1c-927a9947cbf8.png)
![Screenshot 2022-01-24 181547](https://user-images.githubusercontent.com/35975662/150831778-e8e968a7-ddac-4c6d-a924-e5fd03239155.png)
![Screenshot 2022-01-24 181517](https://user-images.githubusercontent.com/35975662/150831782-f12fe8b1-904a-48d6-9735-ea78f4361fa4.png)

**Comment by Globox1997** [comment]
Fixed crash with [https://github.com/Globox1997/LevelZ/commit/cdbc127d613b707904af5df05a6bf16c7ec58058](https://github.com/Globox1997/LevelZ/commit/cdbc127d613b707904af5df05a6bf16c7ec58058) and double tooltip with [https://github.com/Globox1997/LevelZ/commit/21c2759d80374701271f97b29130e0345c212617](https://github.com/Globox1997/LevelZ/commit/21c2759d80374701271f97b29130e0345c212617)
Thanks for reporting
