### ISSUE TITLE
negitive experiance 

### ISSUE THREAD

**Issue by KnightRadiant** [Globox1997/LevelZ#101]
Hi, not sure if this has already been reported or an issue or not but I have just added Dark Enchantment mod to a pack im building for my own use and after using the Dark Enchanting table I checked how much till my next level and noticed I was at -6491. Seems like there is some confilict with how the Dark Enchantment takes the Exp from the player and how LevelZ calculates Exp for the next level unless there is a reason I cant see why LevelZ would put me a negitive Exp.

**Comment by Globox1997** [comment]
This should be fixed with the latest update since levelz doesn't use vanilla xp anymore
