### ISSUE TITLE
game crash when hurting villagers while at max trading level

### ISSUE THREAD

**Issue by urmet** [Globox1997/LevelZ#104]
Game crashes if you have maxed trading level and hurt a villager. throwing a snowball/egg basically nukes your world as loading back in just instantly crashes again. Overpowered bows are slightly better as then the villager dies next time you load the world and crash doesn't happen.

Theory is that it's caused by damage removing villager friend effect and LevelZ trying to apply it back at the same time.

Only LevelZ 1.1.5 and dependencies installed, default configs.

[crash-2022-01-31_23.04.16-server.txt](https://github.com/Globox1997/LevelZ/files/7974249/crash-2022-01-31_23.04.16-server.txt)

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/LevelZ/commit/954b99c90e29748fa1f50916af600a89fa93ce8a](https://github.com/Globox1997/LevelZ/commit/954b99c90e29748fa1f50916af600a89fa93ce8a)
