### ISSUE TITLE
new update make this mod no longer work with clumps mod

### ISSUE THREAD

**Issue by weerawch** [Globox1997/LevelZ#108]
exp splash all over me ToT 
![unknown](https://user-images.githubusercontent.com/73280752/156419213-3db25bbe-6718-43a8-803f-a30e91b1fb26.png)

**Comment by Globox1997** [comment]
What exactly happens there?

**Comment by weerawch** [comment]
> What exactly happens there?

I use clumps mod to compress exp to reduce lag but in the new update this mod does no longer work

**Comment by Globox1997** [comment]
It works but levelz xp is separate to vanilla xp
