### ISSUE TITLE
Levels temporarily set to 0 after entering and leaving modded dimensions

### ISSUE THREAD

**Issue by divinevtwo** [Globox1997/LevelZ#11]
The skill levels reset to 0 every time a player enters or leaves a modded dimension until they relog. It does affect the tools a player can use. This applies too when a player teleports in or out a vanilla dimension without portals. Entering/ leaving a vanilla dimesion with portals works just fine without this bug appearing (this was a previous bug that is already fixed).

**Comment by Globox1997** [comment]
Do you use the latest levelz version? how can I reproduce this bug?

**Comment by divinevtwo** [comment]
I replaced levelz by now with a similar mod but it was version 1.0.5 (the bug still exists in 1.0.6 tho). Reproducing is quite easy, as I stated in the original post, just leave a dimension by any other means than dieing or leaving through a portal (in my case it was teleporting out of it)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/f632d614a3f43f5ef098f8ec57838666b8b43fa6](https://github.com/Globox1997/LevelZ/commit/f632d614a3f43f5ef098f8ec57838666b8b43fa6)
