### ISSUE TITLE
Feature/help request

### ISSUE THREAD

**Issue by Tenchu98** [Globox1997/LevelZ#112]
I am using levels on 1.18.1 in my modpack with origins, I was wondering if there is a way to give a player skill points in a category from datapack.

Ie. If they choose the elven origin automatically assigning them 2 skill points in archery.

**Comment by Tenchu98** [comment]
Or at least is there an attribute I can set from within the origins datapack?

**Comment by Globox1997** [comment]
Maybe you can run a command when the player chooses the origin

**Comment by Tenchu98** [comment]
I haven't seen any examples for running a command within the origins.

**Comment by Tenchu98** [comment]
Is there a way to run a command for an origin?

**Comment by Globox1997** [comment]
Here you go [https://origins.readthedocs.io/en/latest/types/power_types/action_on_callback/](https://origins.readthedocs.io/en/latest/types/power_types/action_on_callback/)

**Comment by Tenchu98** [comment]
thank you

**Comment by Globox1997** [comment]
I guess we can close this issue since origins provide already a way for such a compatibility :)
