### ISSUE TITLE
Crash on death (MC 1.18.2 - LevelZ 1.2.0)

### ISSUE THREAD

**Issue by Cynicizm** [Globox1997/LevelZ#113]
Title says it all.
Happened in a new world, right after I got rammed to death by a Boar from Better Animals Plus.

Tried to replicate the occurrence by getting killed by vanilla mob (Zombie). Same result.

Crash cannot be replicated when LevelZ are uninstalled, so I assumed that it's a bug from this mod (no offense)

[crash-2022-03-27_00.56.47-server.txt](https://github.com/Globox1997/LevelZ/files/8356096/crash-2022-03-27_00.56.47-server.txt)
[crash-2022-03-27_01.16.52-server.txt](https://github.com/Globox1997/LevelZ/files/8356097/crash-2022-03-27_01.16.52-server.txt)
[crash-2022-03-27_01.07.16-server.txt](https://github.com/Globox1997/LevelZ/files/8356098/crash-2022-03-27_01.07.16-server.txt)
.

**Comment by Globox1997** [comment]
Tried to reproduce the error but haven't had luck
Dou have the totem of undying in your hand while dying?

**Comment by Cynicizm** [comment]
> Tried to reproduce the error but haven't had luck Dou have the totem of undying in your hand while dying?

No.

**Comment by Metal-666** [comment]
I'm facing the same issue
[crash-2022-04-05_01.55.58-server.txt](https://github.com/Globox1997/LevelZ/files/8413674/crash-2022-04-05_01.55.58-server.txt)
[crash-2022-04-05_01.59.51-server.txt](https://github.com/Globox1997/LevelZ/files/8413675/crash-2022-04-05_01.59.51-server.txt)

**Comment by Globox1997** [comment]
Maybe I found something.
Can someone check if anything is restricted at all?

**Comment by Metal-666** [comment]
What do you mean?

**Comment by Globox1997** [comment]
If you join a world, press k to get to the levelz screen and check any skill for any restriction, are those all empty? 
By default weapons for example should be unusable and listed under the strength category

**Comment by Metal-666** [comment]
This is how my 'k' screen looks in a new world with default levelz config:
![image](https://user-images.githubusercontent.com/50769245/161747105-5dd3d751-b655-45d3-9c94-7a490274066e.png)
If I hover over Strength it says "Increases Melee Damage. Unlocks Swords"
It's my first time using the mod, so sorry if this is not the info you are looking for

**Comment by Metal-666** [comment]
Also just to add - the crash happens only when dying to a mob (dying to fall damage or berries doesn't crash the game)

**Comment by Cynicizm** [comment]
For me, the item restrictions seemed to be on and worked fine. For instance, I can't use a netherite sword (which I obtained via creative mode during testing) because my Strength/Smithing level isn't sufficient yet.

Note: I can use the sword but it did only 1 damage to any mob.

**Comment by Metal-666** [comment]
I think it might be a compatibility issue. I removed half of the mods I had and the game stopped crashing when I die
Now I'm trying to figure out which mod could be causing this

**Comment by Metal-666** [comment]
Okay, this is very weird
Here is the mod list I ended up with:
![image](https://user-images.githubusercontent.com/50769245/161760141-f0b654e6-2551-4912-9250-12b7c9b39e61.png)
If you run the game with this mods and die to a mob, the game crashes
Removing either Charm or Inspecio fixes the problem
However I don't see Inspecio in Cynicizm's mod list
Which means that there are other mods that can also cause this when used together?
I'm very confused

**Comment by Metal-666** [comment]
Also I have a question about the mod (unrelated to this issue) - where do I get xp to unlock stuff?

**Comment by Cynicizm** [comment]
> Also I have a question about the mod (unrelated to this issue) - where do I get xp to unlock stuff?

I think you get the xp from the usual vanilla xp. That means breeding animals, breaking ores, killing mobs, etc.

But I don't think you get the xp through commands (e.g. /xp add). I tried it and my xp didn't increase at all. Try manually killing a mob, pick up the xp orb, and look at the 'K' screen. Your xp should increase this way.

**Comment by Metal-666** [comment]
> I think you get the xp from the usual vanilla xp. That means breeding animals, breaking ores, killing mobs, etc.

I see...
But I need xp to unlock mining and swords, right? So do I have to punch 50 zombies to death with my fist before I get enough xp to at least unlock mining coal?

> But I don't think you get the xp through commands (e.g. /xp add). I tried it and my xp didn't increase at all. Try manually killing a mob, pick up the xp orb, and look at the 'K' screen. Your xp should increase this way.

I think I saw a command somewhere to change levelz stats...
/playerstats or something like that

**Comment by Cynicizm** [comment]
> > I think you get the xp from the usual vanilla xp. That means breeding animals, breaking ores, killing mobs, etc.
> 
> I see... But I need xp to unlock mining and swords, right? So do I have to punch 50 zombies to death with my fist before I get enough xp to at least unlock mining coal?
> 
> > But I don't think you get the xp through commands (e.g. /xp add). I tried it and my xp didn't increase at all. Try manually killing a mob, pick up the xp orb, and look at the 'K' screen. Your xp should increase this way.
> 
> I think I saw a command somewhere to change levelz stats... /playerstats or something like that

Sorry I don't know man. After the crash I just gave up on Fabric.
Maybe the mod developer can help you on that.

**Comment by Globox1997** [comment]
It is basically a loading issue. For some reason when inspecio and another mod is installed, levelz (and other mods) data won't get loaded to the server. If there is no data on the server, levelz can't sync it to the client and the client tries to read this emptiness.
Next update will fix the crash but the mod will be mostly useless when there is no data on the server.
My guess is, the quilt dependency breaks stuff (inspecio depends on quilt stuff), however the incompatibilities in fabric are definitely a big down side in comparison to forge but in my eyes the performance increase of fabric overweighs it.
/playerstats is the command for levelz

**Comment by Globox1997** [comment]
Reference #117
