### ISSUE TITLE
[Crash] - [Incompatible] - Crashes LevelZ Datapack when Vanilla Hammers & Inspecio & LevelZ are present

### ISSUE THREAD

**Issue by xR4YM0ND** [Globox1997/LevelZ#117]
Hey there,

so this bug is very uncommon 

when you use LevelZ Mod, Inspecio Mod & Vanilla Hammers Mod -> the Datapack for LevelZ doesnt work

"Maybe some Packets are restricted"

Fabric 1.18.2 - 0.13.3

In this latest.log, i hovered over a "bow" and the game crashes. 

This is cause of LevelZ, but this only comes cause the datapack for levelz isnt loaded cause of the combination of vanilla hammers & inspecio

When i use LevelZ with Vanilla Hammers , the Datapack for LevelZ is loaded and all works fine
When i use LevelZ with Inspecio, the Datapack for LevelZ is loaded and all works fine
When i use all 3 (LevelZ , Inspecio & Vanilla Hammers), the Datapack for LevelZ isnt loaded (Packets)

[Latest.Log](https://gist.github.com/SpigotDE/b9e51d8465099029a66a4102f7d3fb60)
[Crash Report](https://gist.github.com/SpigotDE/807412efc1c706c9d7e28132d87fee31)

**Comment by xR4YM0ND** [comment]
Inspecio Issue: https://github.com/Queerbric/Inspecio/issues/72

**Comment by xR4YM0ND** [comment]
Vanilla Hammers Issue: https://github.com/Draylar/vanilla-hammers/issues/115

**Comment by Globox1997** [comment]
This might be fixed since Draylar updated his dependency mod
