### ISSUE TITLE
After death strength lvl stays as it is, but melee damage reduces to default.

### ISSUE THREAD

**Issue by parkurnic** [Globox1997/LevelZ#12]
https://user-images.githubusercontent.com/89710248/131231927-e675ed34-a6de-4c97-b287-2c4b78426634.mp4

**Comment by Globox1997** [comment]
Thanks for reporting, it is really odd but I fixed it with [https://github.com/Globox1997/LevelZ/commit/1bb6e462bd26ea260b6cc6d8f4baa31fcd486e9b](https://github.com/Globox1997/LevelZ/commit/1bb6e462bd26ea260b6cc6d8f4baa31fcd486e9b)
