### ISSUE TITLE
mc dungeons mods

### ISSUE THREAD

**Issue by westorix** [Globox1997/LevelZ#120]
Request to add requirments for weapon and armor sets from mc dungeons mods
I prepared spreadsheet of armors (it also includes some other armors outside of the mc dungeons armors mod)
[ARMORS.xlsx](https://github.com/Globox1997/LevelZ/files/8457493/ARMORS.xlsx)

additional ideas:
- mixed requirments
Example: dark enchanter requirment of levels:
Alchemy 20 | smithing 20
- order by power
modded bows /crosbows would need balance for level requirment 
some bows should even use mix of requirments like archery / alchemy or archery /strengh
armors should require not only Defense but also vitality and strengh
some armors from mods couldd only require archery or mining or agility as requirment

OPTIONAL:
add commend that would add requirment to held item example:
/levelz requirment add Item strength 15
/levelz requirment add block minning 7
- it would create then datapack for the held item with the typed requirment, would be great if u could add multiple requirment suport with it.

I'm tryign to make a balanced rpg focused modpack
and i need to at least have a working datapack for :
- additional additions
- BYG - biomes yo ugo
- Bewitchment 1&2
- mc dungeons weapons | armors | artifacts
- better nether & end

**Comment by Globox1997** [comment]
hey westorix,
actually a dope idea to create datapacks with commands.
However, for mod compat pls ask the mod devs to add compat on their end. it is pretty easy

**Comment by westorix** [comment]
Since my original post i learned how the datapack is manualy done, and i've been playing around with it allot. But i noticed something worrying. Whenever some mod already had requirments on the level and i set datapack to overwrite it, the new requirment was showing on the weapon but the old one was still in place restricting the usage of the weapons.

**Comment by westorix** [comment]
Also currently it seems that there is no way to make multiple requirments on a single item, so the only option for me to properly restrict too op weapons was to increase max level to 50...

**Comment by Globox1997** [comment]
I do have multiple restrictions in mind but not sure when I will add it

**Comment by Globox1997** [comment]
Won't add commands to create a datapack, could be a separate mod.
However for the multiple restrictions I reference this [https://github.com/Globox1997/LevelZ/issues/129](https://github.com/Globox1997/LevelZ/issues/129)
If you have further questions about creating a datapack for levelz, join my discord :)
