### ISSUE TITLE
Feature Inquiry: Can I Add New Sources of Blue XP?

### ISSUE THREAD

**Issue by ghost** [Globox1997/LevelZ#121]
I'm playing this mod with the [mod Artifality ](https://www.curseforge.com/minecraft/mc-mods/artifality) which adds three staffs that drop Vanilla green XP upon using. They, however, do not drop any blue XP from the levelz mod. Can I make it to where these Artifality staffs drop blue XP?

This inquiry is along similar lines as [one posted 29 days ago](https://github.com/Globox1997/LevelZ/issues/111) by Sgievers.

**Comment by Globox1997** [comment]
You can make a compat mod or ask the dev of artifality to use the [https://github.com/Globox1997/LevelZ/blob/1.18/src/main/java/net/levelz/entity/LevelExperienceOrbEntity.java#L110](https://github.com/Globox1997/LevelZ/blob/1.18/src/main/java/net/levelz/entity/LevelExperienceOrbEntity.java#L110) method to spawn levelz xp orbs

**Comment by ghost** [comment]
Excellent. Thank you for your responce and the reasource.
