### ISSUE TITLE
Suggestion: Config - passive stats only

### ISSUE THREAD

**Issue by tadeuszb** [Globox1997/LevelZ#123]
Make an option that will not block any actions when not having leveled up attributes by default - like mining blocks, using buckets, trading with villagers. So if someone does not want such feature won't have to make datapack for it.
So mod will only add passive stats like movement speed, max health, armor etc. with the additional special effects (this is cool addition to max out skills).

**Comment by Globox1997** [comment]
Added config options with [https://github.com/Globox1997/LevelZ/commit/56baad2f59a8fa50c5f070a4d9195ae2ae7a61cb](https://github.com/Globox1997/LevelZ/commit/56baad2f59a8fa50c5f070a4d9195ae2ae7a61cb)
