### ISSUE TITLE
Skill Level tab texture can't be changed

### ISSUE THREAD

**Issue by CreeperPeruano** [Globox1997/LevelZ#125]
I play with a resourcepack but I can't find the texture of the tab anywhere. How do I change it?

**Comment by Globox1997** [comment]
It is located here: [https://github.com/Globox1997/LevelZ/blob/1.18/src/main/resources/assets/levelz/textures/gui/icons.png](https://github.com/Globox1997/LevelZ/blob/1.18/src/main/resources/assets/levelz/textures/gui/icons.png)
