### ISSUE TITLE
SUGGESTIONS 

### ISSUE THREAD

**Issue by TheeMrCheeky** [Globox1997/LevelZ#127]
This mod alone is bad ass but maybe you can get some inspiration from the mod project mmo. You can find it on forge they don't intend on moving it to fabric the last I heard so there are things like gaining xp for wood cutting/farming crops and other cool ideas you could maybe pick up from it :) YOU MAKE WONDERFUL MODS keep up the good work

**Comment by Coyote21** [comment]
And would be nice if we could set our own XP calculation formula in the config file incase someone decides lvl^2 * multi + base is not the formula to use. e.g. might want to use something like exp(multi * lvl) + base.

**Comment by Globox1997** [comment]
Thanks appreciate it :)
I am about to create a job addon for levelz where you gain experience by doing jobs :)
Parsing a string to a formula isn't an easy thing to do which isn't in the scope of this mod
