### ISSUE TITLE
You can use bows at lvl 0 archery

### ISSUE THREAD

**Issue by parkurnic** [Globox1997/LevelZ#13]
https://user-images.githubusercontent.com/89710248/131231975-d416bcf7-f835-496e-b764-1a36c2054068.mp4

**Comment by parkurnic** [comment]
I tried that with crossbow and trident as well, but they're fine.

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/LevelZ/commit/ad6ace7f215d8cbc9b8db6aa9f22701a0eeb2cda](https://github.com/Globox1997/LevelZ/commit/ad6ace7f215d8cbc9b8db6aa9f22701a0eeb2cda)
