### ISSUE TITLE
Level req not applying properly

### ISSUE THREAD

**Issue by Ezekyuhl** [Globox1997/LevelZ#131]
I made a datapack to lower the level requirements of some modded items (Campanion mod, spears)
I was able to lower the level req successfully, however when attempting to use the spears left click function (throw) the game notifies me I must have Archery level 16 (the same level that it had defaulted to initially).

![image](https://user-images.githubusercontent.com/17024553/167812695-c02d19f1-2ae6-4582-b731-a293cf6daa7a.png)

**Comment by Ezekyuhl** [comment]
I added the trident unlock .json from the config and it allowed me to throw the wooden spear, and the higher level ones are not available until the appropriate level, except the trident- it can now be thrown at level 0.

An option to disable all level requirements in the configs would be amazing.

**Comment by Globox1997** [comment]
Added an option for disabling level requirements but I have to fix the trident thingy too

**Comment by Globox1997** [comment]
Probably fixed with [https://github.com/Globox1997/LevelZ/commit/d9624ec5ee1d8e9c0dbc0320537b428ae9f796e1](https://github.com/Globox1997/LevelZ/commit/d9624ec5ee1d8e9c0dbc0320537b428ae9f796e1)
