### ISSUE TITLE
playerstats add progress parameter accepts only integer values

### ISSUE THREAD

**Issue by Coyote21** [Globox1997/LevelZ#134]
Use case: I'm using kubejs to try to award levelz XP when completing achievements/advancements.

I'm not a programmer so I'm basically ripping the code/idea from the Valhelsia: Enhanced Vanilla modpack.

It uses the command "/playerstats <PlayerName> add <skill> <level>" to add skill points. I thought to use "/playerstats <PlayerName> add progress <fraction>" to add XP, except the command only accepts integers. 

Adding "add/remove/set/get xp <xp points>" to the playerstats command would be an ideal solution (as well as changing the progress parameter to float, of course).

Or, is there is an alternative/better method of manually adding levelz XP that I'm ignorant of?

**Comment by Globox1997** [comment]
hey coyote21,
changed the progress command to an experience command with [https://github.com/Globox1997/LevelZ/commit/e4863067d2346435963fdfad00dd2234c99e539a](https://github.com/Globox1997/LevelZ/commit/e4863067d2346435963fdfad00dd2234c99e539a)
I guess this will meet your needs

**Comment by Coyote21** [comment]
Cool, yeah that will work nicely, thanks.

I'd like to wait (patiently) for the next release before I start using it however, just in case.

Is that advisable? or is it unlikely there will be a new release before MC 1.19?

**Comment by Globox1997** [comment]
there will be a release for 1.18.2 :)
