### ISSUE TITLE
[Suggestion] Add option to disable mod

### ISSUE THREAD

**Issue by Vichoriz0** [Globox1997/LevelZ#136]
It would be nice if we could choose in the world creation screen when to enable or disable this mod. For example, players creating a skyblock world would find it impossible to play with this mod enabled, forcing them temporary remove the mod for this world, then having to add it again to play another world in which the player does use it.
With this suggestion implemented, all this hasle could be avoided.

**Comment by TheMightyMcGrew** [comment]
You can already do this by using curseforges mod on/off toggle, or just rename the levelz.jar to levelz.jar.disable

**Comment by TwoPointInfinity** [comment]
just delete the mod.

**Comment by Globox1997** [comment]
Not a bad idea but it is not in the scope of this mod, pls create new instances for it
