### ISSUE TITLE
[Bug] Config partially lost

### ISSUE THREAD

**Issue by xXNickznXx** [Globox1997/LevelZ#137]
I changed the config while in a world. After leaving and rejoining many options were lost.

Some changes that were lost
- changed max level to 10
- changed health base to 10.0
- changed movement bonus to 0.002
- changed farming base to 5
- changed xp base cost to 10

The strange thing is, not everthing was lost, why?

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/06f2790d1bf29251768cf0b9b28227248c6325b4](https://github.com/Globox1997/LevelZ/commit/06f2790d1bf29251768cf0b9b28227248c6325b4)
