### ISSUE TITLE
[Bug] The config cannot be edited in the main menu

### ISSUE THREAD

**Issue by xXNickznXx** [Globox1997/LevelZ#138]
As the title says, it doesnt work.
![image](https://user-images.githubusercontent.com/31235664/170441177-1d249fbc-4db1-4187-9004-45653179b38f.png)

While in a world it works.

Crash report: [crash-client.txt](https://github.com/Globox1997/LevelZ/files/8777207/crash-client.txt)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/06f2790d1bf29251768cf0b9b28227248c6325b4](https://github.com/Globox1997/LevelZ/commit/06f2790d1bf29251768cf0b9b28227248c6325b4)
