### ISSUE TITLE
[Bug/Suggestion] When lowering max level, info is missing/wrong

### ISSUE THREAD

**Issue by xXNickznXx** [Globox1997/LevelZ#139]
[Bug]
I changed the max level to 10.

I noticed, for example, that Netherite tools don't show up in the skill's additional info.
And the tooltip still showed "[Skill] 20" but it gets unlocked at 10.

[Suggestion]
Everything higher than the set max level will unlock at the set max level.
Everything lower is still the same.

I have 2 different suggestions to change that system:
1. Change it so everthing scales with max level. For example something that would unlock at level 4, when changing max level to 10, it would unlock at level 2.
2. Give the option to customize everything via config.
For example:
`
{
"minecraft:netherite-sword": {
"skill": "farming",
"level": 5
}
}
`
In this example i could unlock the netherite sword when the farming skill reaches level 5.

**Comment by Globox1997** [comment]
This happened due to a config syncing issue, fixed with [https://github.com/Globox1997/LevelZ/commit/06f2790d1bf29251768cf0b9b28227248c6325b4](https://github.com/Globox1997/LevelZ/commit/06f2790d1bf29251768cf0b9b28227248c6325b4)
Check out the github readme for more info about levelz datapacks :)
