### ISSUE TITLE
[Suggestion] Option to change the polynomial order for the xp

### ISSUE THREAD

**Issue by ghost** [Globox1997/LevelZ#142]
It would be nice to have the option to change the polynomial order for the xp required to level up. By default, the equation is xp_required = base + lvl^2 (order two polynomial).

**Comment by Globox1997** [comment]
The equation is `lvl^2 * multiplicator + base` but why you wanna be able to change the polynomial?
If I don't forget it, I will add a config for it in the next update, probably for mc 1.19.
Do you want it to be an integer or float?

**Comment by ghost** [comment]
The idea of my suggestion is to be able to make it even harder (or easier) for players to get better stats as they level up. I personally would say an order 3 polynomial works the best, but it should be in the hands of the player or server to decide.
It would be better to be a float number so it can be fine-tuned since the change in 1.0 to the order can already be too impactful at the gameplay.

**Comment by Filaipus** [comment]
Any chance of adding any equation we want?
I played a game as a kid that did `(50/3) * X³ - (100 * X²) + ((850/3) * X) - 200` and I would love to recreate it

**Comment by Globox1997** [comment]
Added an exponent config setting with [https://github.com/Globox1997/LevelZ/commit/aed9eaa5e91e9c4eb64034eaf9977eb02b3f7ea5](https://github.com/Globox1997/LevelZ/commit/aed9eaa5e91e9c4eb64034eaf9977eb02b3f7ea5)
@Filaipus you can open a new issue with such a request but the config lib I use would allow Strings as an input for such a feature and processing a String to a math equation is not that easy.
