### ISSUE TITLE
[Suggestion] RPG Difficulty x LevelZ/PlayerEx difficulty dependent on level

### ISSUE THREAD

**Issue by Balakay420** [Globox1997/LevelZ#144]
Difficulty is dependent on what level you are, and would take the average level of online players in multiplayer 
- within a configurable distance between each other if possible
- configurable +/- level range. ex: say average is level 43, with a config of -5/+10 mobs would spawn between level 38-53)

**Comment by Globox1997** [comment]
This issue should be opened at the RpgDifficulty repository :)
