### ISSUE TITLE
Level requirement for fake players

### ISSUE THREAD

**Issue by rkrgr** [Globox1997/LevelZ#145]
Hey,
I'm using the Valhelsia Enhanced Vanilla modpack version 1.2.3 with LevelZ version 1.3.0. I tried using a deployer from the Mod Create to milk a cow. The deployer acts as a fake player and uses a bucket on a cow. Because the deployer doesn't have farming level 7 the cow isn't milked. By disabling LevelZ my setup works. Is it possible to disable the level requirements for fake players? Thanks for the great mod btw.

Edit: A simple solution would be to turn off the need for having farming to milk cows in the config file I guess. Haven't tried it, but I think shears on a sheep will have the same problem.

**Comment by Globox1997** [comment]
Hi, can you build a super simple test setup and send me a screenshot of it? 
Never used Create and I don't know how it works

**Comment by rkrgr** [comment]
Gladly.

![2022-06-11_15 54 06](https://user-images.githubusercontent.com/9026012/173190968-8367ccf7-1b46-40a1-b825-b31a3a1fdf45.png)
![2022-06-11_15 54 16](https://user-images.githubusercontent.com/9026012/173190979-76a15f9e-2996-462f-b7a9-8165cc05cd34.png)
 
In the upper chest are buckets, which are moved into the Deployer. The Deployer is powered by a Creative Motor and uses the buckets on the cow. You can rotate Create blocks with a wrench. The filled buckets are then moved to the lower chest with a hopper.

**Comment by Globox1997** [comment]
Thanks, I actually just googled it but found pretty much the same structure^^
Fixed with [https://github.com/Globox1997/LevelZ/commit/edbe8a2ed6a7d0d3a9f492328f61455468b772d8](https://github.com/Globox1997/LevelZ/commit/edbe8a2ed6a7d0d3a9f492328f61455468b772d8)
Probably gonna release it soon

**Comment by rkrgr** [comment]
Awesome. Thanks a lot. :D
