### ISSUE TITLE
[Bug] Levels Don't Display Correctly in Creative Menu

### ISSUE THREAD

**Issue by Rage-GitHub** [Globox1997/LevelZ#146]
Custom levels for items don't display correctly in the creative menu. See images for reference.

![image](https://user-images.githubusercontent.com/17907584/172736552-eebabd93-370a-4922-9266-3cd75aaf4806.png)
![image](https://user-images.githubusercontent.com/17907584/172736540-e3a1a889-c88a-4a94-ad79-1d234c8c90de.png)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/d9624ec5ee1d8e9c0dbc0320537b428ae9f796e1](https://github.com/Globox1997/LevelZ/commit/d9624ec5ee1d8e9c0dbc0320537b428ae9f796e1)
