### ISSUE TITLE
[Bug] No Armor Swapping Restriction for Locked Levels

### ISSUE THREAD

**Issue by Rage-GitHub** [Globox1997/LevelZ#147]
Armors that have a level lock have no restriction to being able to right-click equip armors that are locked at a certain level.

https://youtu.be/a4Yq3JrWkqE

**Comment by Globox1997** [comment]
The question is which mod  changes this behavior, any mods installed which allow easy swapping?

**Comment by Rage-GitHub** [comment]
As far as I'm aware, no mod that changes anything regarding swapping. Maybe Trinkets but that's all I can think of.

You can check my [modlist ](https://gist.github.com/Rage-GitHub/124784d102a10323d910244330709d0b)for any mods you may think are a culprit.

**Comment by Globox1997** [comment]
176 is a lot xD 
out of yime reasons I don't try to find incompatibilities for any of my mods, the players who find them have to do that or it will be kept.

**Comment by Rage-GitHub** [comment]
That's fine, I will check through the mods to see each of the functions and see if any of them do alter quick equipping.

**Comment by Globox1997** [comment]
I recommend to use the 50/50 method, so you disable half of the mods every time :)

**Comment by Globox1997** [comment]
For more questions about creating a datapack for levelz check out my discord :)
