### ISSUE TITLE
[Bug] Game crashes on opening skills gui

### ISSUE THREAD

**Issue by RedRedL** [Globox1997/LevelZ#148]
Game will crash when skills menu is opened.
[crash-2022-06-09_19.52.40-client.txt](https://github.com/Globox1997/LevelZ/files/8869253/crash-2022-06-09_19.52.40-client.txt)

**Comment by Globox1997** [comment]
Update levelz and test again

**Comment by RedRedL** [comment]
Updated to 1.3.2 issue still happens

[crash-2022-06-10_12.35.54-client.txt](https://github.com/Globox1997/LevelZ/files/8875334/crash-2022-06-10_12.35.54-client.txt)

**Comment by Globox1997** [comment]
Dang looks like it crashes due to a bug with TooltipRareness mod o_o

**Comment by Globox1997** [comment]
I fixed it on tooltiprareness side
