### ISSUE TITLE
Don't know how to configure items and materials

### ISSUE THREAD

**Issue by PIPILAN** [Globox1997/LevelZ#149]
Sorry, this is not a problem report, I did not understand your tutorial. I don't know how the tag of items works.

> It takes a fifth argument called "material" to determine which material of items will be locked.
Each of these items has to be in the corresponding fabric item tag.

I don't know how to add fabric tag to objects in other mods using crt/kubeJS, or what tag to add to make it work.

Sorry to bother you like this, from Google Translate, there may be some miswording.

**Comment by Globox1997** [comment]
Did you figure it out?

**Comment by PIPILAN** [comment]
> Did you figure it out?

Most of the standard writing methods can be tried out several times, the special mods I guess is not vanilla type, can not be used.

**Comment by Globox1997** [comment]
Than it is the same as [https://github.com/Globox1997/LevelZ/issues/99](https://github.com/Globox1997/LevelZ/issues/99)
