### ISSUE TITLE
[bug?] LevelZ entry point deprecated and Rei warning screen

### ISSUE THREAD

**Issue by CoolNerfDude** [Globox1997/LevelZ#150]
I put Rei and LevelZ together and i got a warning on the screen saying "Warning the entry point used by levelZ, Rei_Plugins is depricated and will be removed in an upcoming version of Roughly Enough Items. Please use "rei_server", "rei_client" , "rei_common" instetad.
_____________
![Screenshot (5)](https://user-images.githubusercontent.com/82691706/173447841-90867860-6edb-4a4e-be3d-c9c5d8f2b384.png)

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/LevelZ/commit/eb41818a6be1c55322017180f343fd97fec0c5ca](https://github.com/Globox1997/LevelZ/commit/eb41818a6be1c55322017180f343fd97fec0c5ca)
