### ISSUE TITLE
Luck's Crit bonus would give you a chance to do REDUCED damage.

### ISSUE THREAD

**Issue by LeGronch** [Globox1997/LevelZ#154]
(disclaimer, I'm not a bright person myself nor knew jack about modding, but I can spot a problem when I see one.)
I was messing with the config files to fit my playthrough and manage to find some flaws along the way. With some testing through using both my modded configs and default config with slight alteration to make debugging easier. I tested without luck increase but with high Luck Crit Bonus increase and vice versa, I manage pinpoint that it was the Crit bonus all along. Even using default configs! 
I tested some other stats too like Stamina health bonus suffering as well, I haven't did some testing as extensive as Crit Bonus. Even when stamina is maxed out it's hard to notice any difference, but I think the default values are too low to add any useful effect. You can ask me any questions.
P.S: I hope luck can increase other perks chance to proc as well, not just crit.

**Comment by Globox1997** [comment]
Hey LeGronch, do you have discord? 
Globox_Z #1024

**Comment by LeGronch** [comment]
> 
My discord is
n3mesi5#0761

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/c9c5f8c62cec44e0c6c84f8d8fe6b4059c8a1ec6](https://github.com/Globox1997/LevelZ/commit/c9c5f8c62cec44e0c6c84f8d8fe6b4059c8a1ec6)
