### ISSUE TITLE
[Suggestion] Add LevelZ lvl criteria for scoreboard

### ISSUE THREAD

**Issue by FlapT** [Globox1997/LevelZ#155]
Add the LevelZ lvl as a criteria for the scoreboard, so players can see the lvl above each others head, or make a new space next to the name like in a rpg.

**Comment by TwoPointInfinity** [comment]
oh yes please.

**Comment by Globox1997** [comment]
[levelz-1.3.7.zip](https://github.com/Globox1997/LevelZ/files/9009243/levelz-1.3.7.zip)
Can you guys test this? Added a criteria and a playerlist addition

**Comment by FlapT** [comment]
Works fine so far, only problem is that you have to set the start lvl manually when you create a new criteria with "levelz", since it only tracks if you lvl up, not the current lvl of the player. Is there a way to deactive the standard level list on server side, or does everyone have to deactivate it manually?

**Comment by Globox1997** [comment]
I never worked with criterias. What exactly is the problem, I don't understand?

**Comment by FlapT** [comment]
At the moment the lvl will be automatically shown in the scoreboard next to each players name, you can deactivate it on the client side but you can't deactivate it for all players on the server, on the server side. So if you just want the people to see lvl shown beneath der names, when you meet each other player, every player has to deactivate the standard scoreboard listing in the mods config.

**Comment by Globox1997** [comment]
Not sure if we talk about the same scoreboard

**Comment by FlapT** [comment]
At the moment the standard settings will show the lvl on the list display when you press tab. You can only disable that if every player disables this option in the config and it doesn't matter if it's activated or deactivated in the server config. It would be nice to decide that on the server side though, for example if you only want the players to be able to see each others lvl when they meet each other. Hope it's more clear with this explanation^^

**Comment by Globox1997** [comment]
Ah okay you are talking about the playerlist :)
Scoreboard is this https://minecraft.fandom.com/wiki/Special:MobileVisualEditor?page=Scoreboard
Since it is a client setting, I think it is okay to see the lvl of other players
I can try to add the lvl next to the playername too

**Comment by FlapT** [comment]
Yeah, next to the Playername would be pretty nice :)

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/LevelZ/commit/9f344dd0723df77b9418e592932ddabbbde1f98c](https://github.com/Globox1997/LevelZ/commit/9f344dd0723df77b9418e592932ddabbbde1f98c)
