### ISSUE TITLE
[Suggestion] Increase XP pick-up rate

### ISSUE THREAD

**Issue by rChaoz** [Globox1997/LevelZ#156]
Late in the game, when I have like level 200, it's incredibly difficult to level up, I need to grind for hours and a big part of that is simply waiting to pick-up the XP orbs, sometimes I have to afk for 5 minutes after grinding to just wait for the orbs to be picked up. It would be nice if XP could be picked up faster (blue XP especially), as that late in the game it simply isn't fun to be late-game in every mod and still have to grind for hours for some levels.

**Comment by TwoPointInfinity** [comment]
pls pls pls. Or a config option that when enabled would clump xp orbs together so it can all be collected instantly. Would be better for server entities too.

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/LevelZ/commit/77bfa06d5b1ed88afbfc2996f5fcc0ab7411927e](https://github.com/Globox1997/LevelZ/commit/77bfa06d5b1ed88afbfc2996f5fcc0ab7411927e)
