### ISSUE TITLE
it crashes when i try to enchant a netherite sword 

### ISSUE THREAD

**Issue by ShadowSlayerFX1** [Globox1997/LevelZ#158]
minecraft version 1.18.2
mod versionb 1.3.3
log
https://drive.google.com/file/d/1UEUsjzO-Abrfw7tDB771tqstX-gNb10n/view?usp=sharing

**Comment by Globox1997** [comment]
If I remember correctly you have to downgrade levelz to 1.3.2

**Comment by Globox1997** [comment]
Reference [https://github.com/Globox1997/LevelZ/issues/169](https://github.com/Globox1997/LevelZ/issues/169)
