### ISSUE TITLE
LevelZ and Redstone Bits incompatability.

### ISSUE THREAD

**Issue by Dragonracer1973** [Globox1997/LevelZ#159]
No crash here, just that because the redstone bits breaker is (I assume) coded as a player entity, it voids broken blocks, rather than dropping them.

**Comment by Globox1997** [comment]
Yea it is a fake player entity, reference [https://github.com/Shnupbups/redstone-bits/blob/17b3403b074c79100502645fd294fd3542704e61/src/main/java/com/shnupbups/redstonebits/FakePlayerEntity.java#L11](https://github.com/Shnupbups/redstone-bits/blob/17b3403b074c79100502645fd294fd3542704e61/src/main/java/com/shnupbups/redstonebits/FakePlayerEntity.java#L11) and [https://github.com/Shnupbups/redstone-bits/blob/1.18.2/src/main/java/com/shnupbups/redstonebits/blockentity/BreakerBlockEntity.java#L213](https://github.com/Shnupbups/redstone-bits/blob/1.18.2/src/main/java/com/shnupbups/redstonebits/blockentity/BreakerBlockEntity.java#L213)

**Comment by Globox1997** [comment]
[levelz-1.3.7.zip](https://github.com/Globox1997/LevelZ/files/9071203/levelz-1.3.7.zip)
Pls test this version for me

**Comment by Dragonracer1973** [comment]
Than you I'll get on this and report this weekend.

**Comment by Dragonracer1973** [comment]
Do you want me to test on 1.19, because I can, just wondering as the report was for version 1.18.2

**Comment by Dragonracer1973** [comment]
Still voiding, but 1.19 is working :)
![2022-07-09_06 28 06](https://user-images.githubusercontent.com/50302305/178103673-01e6e615-bb8d-4da4-9334-d6cf33cd817d.png)
![2022-07-09_06 28 04](https://user-images.githubusercontent.com/50302305/178103681-38aff23d-dbae-45a4-be4c-4fa3eb8c101d.png)
![2022-07-09_06 28 00](https://user-images.githubusercontent.com/50302305/178103718-ac92284d-e3b6-4068-b91c-8f6363124e43.png)

**Comment by Dragonracer1973** [comment]
FYI I am willing to keep testing, tho I have a potatoe for a P.C. I can slap a pack together pretty quickly with Multi Mc

**Comment by Globox1997** [comment]
What do you mean with 1.19 is working?
The version I sent is for mc 1.19

**Comment by Globox1997** [comment]
Pls reopen with further information
