### ISSUE TITLE
Unexpected crashes when opening inventory.

### ISSUE THREAD

**Issue by TheRobberPanda** [Globox1997/LevelZ#160]
[crash-2022-07-09_15.56.17-client.txt](https://github.com/Globox1997/LevelZ/files/9077270/crash-2022-07-09_15.56.17-client.txt)
Using fabric on a SMP
1.18.2

**Comment by Globox1997** [comment]
I wonder how this happens o_o
It does check for null here: [https://github.com/Globox1997/LevelZ/blob/1.19/src/main/java/net/levelz/mixin/item/ItemStackClientMixin.java#L67](https://github.com/Globox1997/LevelZ/blob/1.19/src/main/java/net/levelz/mixin/item/ItemStackClientMixin.java#L67)

**Comment by Globox1997** [comment]
Out of time reasons I only work on the latest version, so I can only recommend to update to 1.19.2
