### ISSUE TITLE
Level requirements randomly change on server

### ISSUE THREAD

**Issue by Siddiqbey21** [Globox1997/LevelZ#161]
There is an issue where when my server gets restarted, the level requirements for tools, weapons, armor, etc., seem to get changed. For example, a diamond sword normally required a strength level of "16". For some reason though, sometimes after restarting my server, it would be changed to a requirement of "28". The problem here is that we have our max levels set to "20", so it's impossible to get it.

Sure, we can change the max level, but sometimes the levels go back to "16" from "28" which would make it pointless or overpowered. I don't know if there is a way to keep the values static in the config file, since I couldn't find anything. Not sure if this is a bug or intentional either. 

Please let me know if there is anything I can do on my end. Thanks,

**Comment by Globox1997** [comment]
That sounds really odd, do you have any datapacks installed on your server?
