### ISSUE TITLE
Strange Potion

### ISSUE THREAD

**Issue by Hideout28** [Globox1997/LevelZ#162]
I have been playing the newest Valhesia pack with LevelZ and was wondering exactly how I get Strange Potions as I would like to reset some skills, is it a rare drop like the Rare Candy, or do I have to make it? If I do, REI does not show how.

**Comment by Globox1997** [comment]
You have to put dragon breath and a nether star into the brewing stand
Added rei compat with [https://github.com/Globox1997/LevelZ/commit/0c55f6b88bdd6bb7e05831a065f735c28f681a14](https://github.com/Globox1997/LevelZ/commit/0c55f6b88bdd6bb7e05831a065f735c28f681a14)
