### ISSUE TITLE
1.18.2  Not awarded points.

### ISSUE THREAD

**Issue by ReapingOculus** [Globox1997/LevelZ#163]
When completing some achievements that would normally award points into specific skills. The points are not actually being awarded, I am not sure if it's a config issue but as it seems to tell me I am awarded it in chat, it is working mostly as intended.
![LevelZ1](https://user-images.githubusercontent.com/96462839/178926001-27220091-210c-44e1-b547-9c9df59f98d1.PNG)
![2022-07-14_00 22 53](https://user-images.githubusercontent.com/96462839/178926058-321b4b0d-3146-41ea-9ce6-4550cef6f80e.png)
.

**Comment by Globox1997** [comment]
Let me see the datapack which tries to do this

**Comment by Vaelzan** [comment]
You can close this issue, this is a custom KubeJS script that I wrote specifically for Valhelsia: Enhanced Vanilla and that I've been maintaining for the pack as mods update (including fixing this issue when KubeJS changed some things regarding the way text works).

Anybody encountering this problem should update to the latest version of Valhelsia: Enhanced Vanilla (or if you're seeing that in a different modpack, they're stealing my scripts). If they still have problems, please contact me on the Valhelsia Discord and I can take a look at the KubeJS logs.

**Comment by Globox1997** [comment]
Thanks, appreciate it
