### ISSUE TITLE
【suggestion】Make Hunger and saturation relate to Level

### ISSUE THREAD

**Issue by blood789** [Globox1997/LevelZ#166]
Make Hunger and saturation relate to Level, similar to Health.

At the start of the game, player only have 3 heart and 3 food level.

**Comment by NickMineBoom** [comment]
i think the stamina skill tree is related to that

**Comment by Globox1997** [comment]
Not a bad idea but this isn't in the scope of this mod.
The stamina skill will decrease the hunger a little
