### ISSUE TITLE
Suggestion: remove hardcoded smithing skill restriction on smithing recipes

### ISSUE THREAD

**Issue by emihead** [Globox1997/LevelZ#168]
I'm trying to use this mod to gate the tool progression behind the mining skill specifically. Seeing as how the smithing system is basically crafting with a different coat of paint, I don't see why the recipe restrictions have to be hardcoded to the smithing skill.

**Comment by Jurklein** [comment]
I believe you could change this with a cusotm datapack, no?

```
{
    "replace": false,
    "level": 20,
    "item": [
        "minecraft:netherite_sword",
        "minecraft:netherite_pickaxe"
    ]
}
```

Or maybe I misunderstood your question =P

**Comment by Globox1997** [comment]
if you wanna restrict crafting recipes you can use this [https://github.com/Globox1997/LevelZ#7-crafting-since-version-130](https://github.com/Globox1997/LevelZ#7-crafting-since-version-130)
