### ISSUE TITLE
Levelz not recognizing Dark Enchanting

### ISSUE THREAD

**Issue by SharkieTV** [Globox1997/LevelZ#17]
When Enchanting with a another mod block called Dark Enchanting it uses levelz xp and makes it go to -40,000

**Comment by parkurnic** [comment]
It's called incompatibility, you see authors can't watch all for their mod to be compatible with all others, so issues WILL happen.

**Comment by SharkieTV** [comment]
I just reported it? Not sure why you so angry

**Comment by Globox1997** [comment]
I will look into it when I get home from vacation

**Comment by Globox1997** [comment]
Found the issue: dark enchanting uses the addExperience method which a normal anvil doesn't use but I inject code to the addExperience method which will reduce the player level experience of levelz
here: [https://github.com/frqnny/dark-enchanting/blob/11cb59a0db848156c18809ef17fa742431043c79/src/main/java/io/github/frqnny/darkenchanting/util/XPUtil.java#L108](https://github.com/frqnny/dark-enchanting/blob/11cb59a0db848156c18809ef17fa742431043c79/src/main/java/io/github/frqnny/darkenchanting/util/XPUtil.java#L108)
I could check if the addExperience method will reduce the amount but then negative xp orbs wouldn't work...
The vanilla anvil uses the addExperienceLevels method for reference

**Comment by Globox1997** [comment]
This is fixed in a later version (mc 1.18.2+) since levelz uses a new xp system :)
