### ISSUE TITLE
【suggestion】Add a config option to set a Maximum Player lvl

### ISSUE THREAD

**Issue by v1-c705** [Globox1997/LevelZ#171]
I think it would be great to add an option to set a maximum player lvl. The reason beeing that it would be possible for modpack creators to force players to focus in different builds as to promote cooperation between them, and not everyone eventually being good at everything. I really love this mod and hope that you find my suggestion interesting!

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/LevelZ/commit/aaa8e0bf0ea24048baf395ffb6b6ed2c99b57169](https://github.com/Globox1997/LevelZ/commit/aaa8e0bf0ea24048baf395ffb6b6ed2c99b57169)
It is called Overall Max Level
