### ISSUE TITLE
Issue with Alchemy/Exhaustion Leveling

### ISSUE THREAD

**Issue by athenashield** [Globox1997/LevelZ#174]
Hello. I am coming here to report a really aggravating issue that happens only once the player levels either Alchemy or Exhaustion.

Upon leveling up either stat, the player starts taking one heart of damage every second or two, the Strength and Haste II potion/beacon effects flicker on and off every few seconds with a duration of one second each, and randomly blocks behind the player will spontaneously ignite.

I do not know what is causing this, but it is truly frustrating as it makes the mod practically unplayable if you wish to level up your Alchemy.

Is there a way to resolve this issue? Is this intentional?

**Comment by athenashield** [comment]
I'm using one of PwrDown's modpacks, should I list all mods in the pack?

**Comment by Excalica** [comment]
Update the version in these modpack to levelz 1.0.15

**Comment by athenashield** [comment]
That fixed the issue! Thank you!
