### ISSUE TITLE
Is there a config to specify amount of exp drops per mob?

### ISSUE THREAD

**Issue by Mcmanybucks** [Globox1997/LevelZ#175]
Currently it feels like it's wayy too little, and because of the modpack I'm playing with a ton of blocks are inaccessible due to my low level..

**Comment by Globox1997** [comment]
Check out the config settings :)

**Comment by Globox1997** [comment]
You can decrease the base cost which is called xpBaseCost and/or increase the mob xp drop which is called mobXPMultiplier
