### ISSUE TITLE
Problems with kubejs and awarding points. May be a duplicate of #163

### ISSUE THREAD

**Issue by Coyote21** [Globox1997/LevelZ#177]
I'm having same issue as #163, but for me it's any kubejs script that uses either event.server.runCommand() or event.server.runCommandSilent() to give points/skills.

e.g.
```
event.server.runCommand(`/playerstats ${event.player.name} add ${rewardData.skill} ${rewardData.points}`);
```
does not do anything, no errors, no points, nothing.
However

```
event.server.runCommand(`/playerstats PLAYERNAME add smithing 1`);
```
(replacing PLAYERNAME with actual playername)
does work.

I have attached my entire kubejs folder b/c it contains all the scripts that are no longer working, in context.

(You will probably recognise them as slightly modified valhelsia scripts b/c thats where I ripped them from.)
I have left my troubleshooting code in, in case it's of any use.

The two important scripts are server_scripts/first_start.js which gives players their starting 3 points and server_scripts/advancements/rewards.js which gives players points based on advancements earned.

This was all working fine with 1.3.0 for sure, and I'm reasonable sure it was working with 1.3.2 as well. I have tried rolling back to 1.3.0 
but this did not solve the problem. This might make you think the issue is with kubejs, except there have been no other cases reported which is unlikely if one of their more important methods just stopped functioning correctly.

[kubejs.zip](https://github.com/Globox1997/LevelZ/files/9299345/kubejs.zip)

As always let me know if you need anything more.

**Comment by Coyote21** [comment]
Update: kubejs devs responded as below…

> event.player.name returns a Component rather than a String now (it used to be a Text iirc), you can use Component.getString() to get the name as a string (that's event.player.name.string in total)


So looks like issue may have nothing to do with Levelz. Will continue to test tonight and will close this issue if I find a solution.

**Comment by Coyote21** [comment]
Update: Using ```${event.player.name.string}``` instead of ```${event.player.name}``` as suggested by kubejs devs fixes the issue.

e.g
```event.server.runCommand(`/playerstats ${event.player.name.string} add ${rewardData.skill} ${rewardData.points}`);```

So NOT a Levelz issue, sorry about that. But maybe this will help others in future..

**Comment by Globox1997** [comment]
Thank you very much for such a good explanation :)
