### ISSUE TITLE
【SUGGESTION】ADD A HWYLA TYPE FEATURE FOR MINING AND HARVESTING BLOCKS

### ISSUE THREAD

**Issue by tiigerbones** [Globox1997/LevelZ#179]
would be neat instead of the highlight block red feature that we currently have.
could display the tool and mining/harvesting level needed and the block that is being mined or harvested

**Comment by Globox1997** [comment]
It has already a feature like that with WTHIT

**Comment by tiigerbones** [comment]
> It has already a feature like that with WTHIT

oh nice, thanks for letting me know!

**Comment by Globox1997** [comment]
You are welcome :)
