### ISSUE TITLE
Massive Datapack Issue

### ISSUE THREAD

**Issue by Jurklein** [Globox1997/LevelZ#180]
I'm having trouble with my (massive) datapack. I noticed some of the added config rules are not being implemented by LevelZ, and I could not find any typos.
It seems like when the custom entity/block/item/list array is too large, the last elements in the array are simply discarded.

Take, for example, the block/mining/level_14.json:
```
...
        "byg:blue_nether_brick_bricks",
        "minecraft:lapis_block",
        "immersive_weathering:prismarine_brick_wall",
        "immersive_weathering:prismarine_brick_slab",
        "immersive_weathering:prismarine_bricks",
        "betternether:bone_wall",
        "betternether:bone_slab",
        "betternether:bone_pillar",
        "betternether:bone_ladder",
        "betternether:bone_fence"
    ]
}
```
All of these entries are not being grabbed by the mod. What could be the issue?

I intend to release this datapack for public use, and I attached its current state here, to help in your analysis.

**Comment by Jurklein** [comment]
[bhl_levelz.zip](https://github.com/Globox1997/LevelZ/files/9398436/bhl_levelz.zip)

**Comment by Jurklein** [comment]
The modpack under which the datapack is being tested.
[better hard level 1.18.2-1.0.zip](https://github.com/Globox1997/LevelZ/files/9398458/better.hard.level.1.18.2-1.0.zip)

**Comment by xR4YM0ND** [comment]
can you add a vanilla item at the bottom of the list (e.g. minecraft:stone) and test after reloading if the stone is changed

**Comment by xR4YM0ND** [comment]
obvioulsy remove the minecraft stone from other entries if you have used it before

**Comment by xR4YM0ND** [comment]
Turns out some ids are incorrect. Hit me up on Globox's Discord "※`RAY´※" https://discord.gg/ZGRDBv3fFg

**Comment by Jurklein** [comment]
Thanks for your observation, @SpigotDE . Indeed, there were some wrong ids. My mistake on the ticket opening as well, as all I had to do was to reload the changed datapack for it to be reflected in-game. This issue can be closed.
