### ISSUE TITLE
Remove Invalid ID's from Skill Level Tree

### ISSUE THREAD

**Issue by Jurklein** [Globox1997/LevelZ#182]
Basically, the request is to remove the invisible "Air" block from the skill tree unlockable blocks/items view (the one which opens when the player clicks over one skill, and then on the top-right corner) if the block/item ID is invalid.

The reason for this is simple: for datapacks that are procedurally generated, there may be some autogenerated ID's which don't match any existing block/item; this is true especially for modded environments, with mods that add many blocks. For these scenarios, the unlockables view generates poorly, as in the evidence that follows.

Evidence:
![image](https://user-images.githubusercontent.com/32760403/186794054-fd95dd1d-bdea-4598-a5d7-d8d2b099e622.png)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/aaa8e0bf0ea24048baf395ffb6b6ed2c99b57169](https://github.com/Globox1997/LevelZ/commit/aaa8e0bf0ea24048baf395ffb6b6ed2c99b57169)
Thanks for reporting
