### ISSUE TITLE
Level Requirement displaying when at max level

### ISSUE THREAD

**Issue by micrwvae** [Globox1997/LevelZ#184]
when maxing out all the categories the red text with the level requirements for that item still displays 
this is only visual and does not prevent the tool from beeing used

**Comment by Globox1997** [comment]
Which version do you use?

**Comment by micrwvae** [comment]
1.3.7 on both client and server

**Comment by Globox1997** [comment]
are you talking about custom items?

**Comment by micrwvae** [comment]
if u mean tools from other mods like for example the trident variations from Impaled yes it displays on there
iirc not on the tools from Warden loot tho
but i also saw the requirement line on the vanilla bow

**Comment by xR4YM0ND** [comment]
can you provide a picture

**Comment by micrwvae** [comment]
welp the line is gone now
the only thing i did was update another mod and restart the server
