### ISSUE TITLE
[Compatability] Sprint-o-Meter mod

### ISSUE THREAD

**Issue by CasualJeremy** [Globox1997/LevelZ#185]
It would be awesome if your stamina level increases the stamina bar from the Sprint-o-Meter mod

https://www.curseforge.com/minecraft/mc-mods/sprint-o-meter

**Comment by Globox1997** [comment]
Can't write the dev on discord cause of disabled pm
you could open an issue on their discord

**Comment by CasualJeremy** [comment]
I can't find a link to their Discord but I private messaged them on CurseForge. It appears as though they have been absent since mid-August but fingers crossed they'll get back to me soon

**Comment by SylisMC** [comment]
You could also post something in their issue tracker. It is available
