### ISSUE TITLE
when dying in nether i loose all levels after respawning with other mods

### ISSUE THREAD

**Issue by Fortnisphere** [Globox1997/LevelZ#186]
https://www.mediafire.com/file/gss1gssgnzicanz/RIFT_SMP_MODPACK-_%2528Special_Edition%2529.zip/file heres the modpack being used

**Comment by Fortnisphere** [comment]
the only way to fix it is by eating a rare candy

**Comment by Fortnisphere** [comment]
or leaving and rejoining which i just found

**Comment by Fortnisphere** [comment]
nvm its actually whenever you switch dimensions you don't need to die for it to cause problems

**Comment by Globox1997** [comment]
which mod version do you use?
