### ISSUE TITLE
1.18.2 v1.3.3 Config not working as intended.

### ISSUE THREAD

**Issue by ReapingOculus** [Globox1997/LevelZ#189]
I checked the config and its set to 3 hearts (6HP). Yet when I load into a world, I have full heart values and regen my health as if I am low HP.
[LevelZ.txt](https://github.com/Globox1997/LevelZ/files/9561590/LevelZ.txt)

**Comment by ReapingOculus** [comment]
Its the same on my server with default config.

**Comment by Globox1997** [comment]
Out of time reasons I only work on the latest version of my mods. I recommend to update to 1.19.2 or at least to the latest 1.18.2 version, however this will have other bugs
