### ISSUE TITLE
Data Pack Custom Materials

### ISSUE THREAD

**Issue by Elska85** [Globox1997/LevelZ#190]
I've played around with this quite a few times but is there a way to add custom materials to this list for data packs. For example I'm using better end's aeternium material as a level 20 unlock,

{
    "replace": true,
    "skill": "defense",
    "level": 20,
    "item": "minecraft:custom_item",
    "object": "betterend:armor",
    "material": "aeternium"
}

Is it the formatting, or is this something not possible yet with the data pack structure?

**Comment by Globox1997** [comment]
Check out my discord for help :)
either you can use object or material and I always recommend to use the material id if possible.
with the /info material command you get the material id (dev mode on the latest version)

**Comment by Elska85** [comment]
> Check out my discord for help :) either you can use object or material and I always recommend to use the material id if possible. with the /info material command you get the material id (dev mode on the latest version)

Thank you, I was unaware of that command. Thanks for getting back to me. Love your mods and I hope you keep up the amazing work.
