### ISSUE TITLE
Real xp doesnt match skill xp

### ISSUE THREAD

**Issue by kittech0** [Globox1997/LevelZ#192]
The problem is when someone get xp through example command or mod directly adding the xp and it doesnt add up to skill xp

**Comment by huanzejin** [comment]
是的，我也发现了这个问题

**Comment by Globox1997** [comment]
yes this is correct, therefore are levelz xp commands since levelz switched to its own experience

**Comment by kittech0** [comment]
Is there way to make it use minecraft xp?

**Comment by Globox1997** [comment]
With the coming update there will be a config setting for it, made by LangYue
