### ISSUE TITLE
Incompatible with CC Restitched mod

### ISSUE THREAD

**Issue by Midnight-GHub** [Globox1997/LevelZ#195]
CC Restitched mod is a port of CC Tweaked mod to fabric. this mod adds programmable computers and bots called turtles which can be equipped with diamond gear.
Issue - the turtle bots are considered as player so they are stuck at level 0 which means the blocks broken by them are not being picked up.
video link - https://drive.google.com/file/d/1XYzeYHMVy8iBO2iovuvTR3l8SUKlvvvh/view?usp=sharing

**Comment by Globox1997** [comment]
[levelz-1.4.1.zip](https://github.com/Globox1997/LevelZ/files/9809301/levelz-1.4.1.zip)
try this, unzipping needed

**Comment by Midnight-GHub** [comment]
That's for version 1.19.2. I need 1.18.2. Testing it anyway

**Comment by Kiwi-Co** [comment]
TYSM! It works but can you please back port it to 1.18.2.
video - https://user-images.githubusercontent.com/111125019/196507362-b601e11f-d4b8-4dbd-9031-9c3d6c9e813e.mp4
