### ISSUE TITLE
Limited crafting question

### ISSUE THREAD

**Issue by CapitainSmasher** [Globox1997/LevelZ#197]
Hello!

I have a question about crafting.

On my onwn modpack i have install advanced netherite mod. I use Kubejs and your mod to config this mod.
like you cannot use netherite iron sword if you don't have 35 lvl in strenght. But i have a problem with crafting. you can craft any item in game if you have components whitout skill to use.

So there is my question: Can you limit crafting item if you don't have skill to use for ?

thanks you very much for your futur answer.

best regards

**Comment by Globox1997** [comment]
Yes, here we go [https://github.com/Globox1997/LevelZ#7-crafting-since-version-130](https://github.com/Globox1997/LevelZ#7-crafting-since-version-130)

**Comment by CapitainSmasher** [comment]
thanks your for your answer.

i don't understand what have supposed to do with this cause i'm beginner, sorry. If you want i can send you that:

{
    "replace": true,
    "skill": "smithing",
    "level": 25,
    "item": "minecraft:custom_item",
    "object": "advancednetherite:netherite_iron_ingot"
}

it's in levelZ/ item. Crafting category isn't a document right ?

So what can i do ?

**Comment by Globox1997** [comment]
check out my discord :)

**Comment by CapitainSmasher** [comment]
thanks you =)
