### ISSUE TITLE
[Bug] Health not updating

### ISSUE THREAD

**Issue by SylisMC** [Globox1997/LevelZ#2]
Whenever a player joins the game for the first time their health is displayed as normal (10 full hearts) their health isnt properly set to 3 hearts until a health update check is triggered. Ea taking/receiving damage.

I think this is a mildly critical issue because players are taking fall damage from 4 blocks and jumping from 10 hearts to 2, it's quite a jarring change if you don't know its coming, Falling for A mear 3 hearts of damage would kill you outright, and that's a bit extreme when you can visually see you have 10 hearts... especially for hardcore players

Ive resolved this with a datapack for my server by triggering `/effect give @p minecraft:instant_health`  on any new player that joins.

You can resolve this issue permanently by adding a line to trigger a health update when a player first joins the world

**MC1.17.1
levelz-1.0.0.jar**

**Comment by Globox1997** [comment]
Thank you for reporting this bug and the good information about it :)
Fixed it with [https://github.com/Globox1997/LevelZ/commit/7283aba6dcd521de2626506e6805edba51796a5a](https://github.com/Globox1997/LevelZ/commit/7283aba6dcd521de2626506e6805edba51796a5a)
