### ISSUE TITLE
Error while trying to connect to server

### ISSUE THREAD

**Issue by willko22** [Globox1997/LevelZ#201]
Hello.
When i try to connect to  my server, while both server and client has LevelZ, i got an **error:**
![unknown](https://user-images.githubusercontent.com/63810279/199695891-72774c16-dc6a-41b8-bce1-6df1fd9f07bf.png)

**Mods installed:**
- levelz-1.4.0
- badpackets-fabric-0.2.0
- cloth-config-8.2.88-fabric
- fabric-api-0.60.0+1.19.2
- HealthOverlay-1.19.2-7.1.1
- wthit-fabric-5.12.0

**Server Log:**
[latest-server.log](https://github.com/Globox1997/LevelZ/files/9927335/latest-server.log)
**Client Log:**
[latest-client.log](https://github.com/Globox1997/LevelZ/files/9927336/latest-client.log)

**Comment by Globox1997** [comment]
What happens if badpackets is not installed

**Comment by willko22** [comment]
sorry wrong answer before.

if there isnt badpackets, the WTHIT cant work. 
your mod has WTHIT in relations.

if LevelZ doesnt need WTHIT then i can remove it.

**Comment by Globox1997** [comment]
Mh it should work with it but it is not hard dependend

**Comment by willko22** [comment]
Ok tested.
LevelZ works without it.
Connection ERROR still poping up

**Comment by willko22** [comment]
okej so the problem was in my stupidity.
when u install fabric u get 2 server files. i didnt notice.
so i the whole time was starting vanilla server instead of fabric.
AAAAAAAAAAAAAAAAh
