### ISSUE TITLE
[Feature Request] - Jade compat

### ISSUE THREAD

**Issue by xR4YM0ND** [Globox1997/LevelZ#206]
Hello hello, i am tim

pls jade compat that shows the values like WTHIT does

**Comment by Globox1997** [comment]
I am Mark

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/LevelZ/commit/37ca504e08cbe2d7dca3a40c6bc46e83726b5440](https://github.com/Globox1997/LevelZ/commit/37ca504e08cbe2d7dca3a40c6bc46e83726b5440)
