### ISSUE TITLE
[Feature Request] - Standalone HUD Text 

### ISSUE THREAD

**Issue by xR4YM0ND** [Globox1997/LevelZ#207]
Hello hello, i am marc

Pls a standalone hud text for "locked" & "mineable level ..."

**Comment by Globox1997** [comment]
I am Tim

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/LevelZ/commit/a649cfe27f9ef6a272cf2c0b7bb00574239eafe1](https://github.com/Globox1997/LevelZ/commit/a649cfe27f9ef6a272cf2c0b7bb00574239eafe1)
