### ISSUE TITLE
(Issue) Netherite,Iron and Diamond Tools

### ISSUE THREAD

**Issue by 12MBTT** [Globox1997/LevelZ#209]
(X>Golden) items dont show how much strength (etc.) level do we need, and dont cancel their use. 

![2022-11-10_17 52 23](https://user-images.githubusercontent.com/117925144/201128716-0903b9c7-b0dc-45e2-bfaa-ba81b9e68412.png)

![2022-11-10_17 57 31](https://user-images.githubusercontent.com/117925144/201128791-0200dca2-3e4d-47e1-9db7-7f917f41b8f8.png)

I thought I would wix with creating datapack for it but it doesnt work and even it shows only on custom levelz screen 

![2022-11-10_17 57 14](https://user-images.githubusercontent.com/117925144/201130795-98247122-c868-469d-a090-7a8c48054d98.png)

![2022-11-10_17 52 58](https://user-images.githubusercontent.com/117925144/201130929-6ca7af1f-d30e-4d64-825a-9eb731a0f838.png)

and theres incredible things in going on with smithing!!

![2022-11-10_17 57 10](https://user-images.githubusercontent.com/117925144/201131378-80f5d246-87a3-4d3a-8e73-93c9f16d537a.png)

![2022-11-10_17 59 28](https://user-images.githubusercontent.com/117925144/201131495-1fd545f7-6afb-48c0-8323-21d61b42d328.png)

as u can see, we can craft netherite sword with smithing level 20 and 60!
I tried to set my smithing level 20 and it doesnt work but when I set smithing 60,its working but doesnt show 
on inventory

Btw, I have 0 levels on every skill

Pls fix that.I will be greatful :) <3 
(Sorry if I did mistake in english)

**Comment by Globox1997** [comment]
Does this happen with only levelz installed and do you use a custom datapack?

**Comment by 12MBTT** [comment]
every single of them D:

**Comment by 12MBTT** [comment]
> Does this happen with only levelz installed and do you use a custom datapack?

I use couple of datapacks of my mods I'll try to remove them and send back after

**Comment by 12MBTT** [comment]
> > Does this happen with only levelz installed and do you use a custom datapack?
> 
> I use couple of datapacks of my mods I'll try to remove them and send back after

didnt work.

**Comment by 12MBTT** [comment]
> Does this happen with only levelz installed and do you use a custom datapack?

![2022-11-10_20 33 57](https://user-images.githubusercontent.com/117925144/201167731-4cc80e00-0bda-465d-a128-272df744b1df.png)
![2022-11-10_20 34 25](https://user-images.githubusercontent.com/117925144/201167748-e1350471-4067-474e-8d1b-a604d8edfdcd.png)
 This is just fabric api, levelz and cloth config api with unchanged config.
