### ISSUE TITLE
[Bug (easy fix)] LevelZ stats not updating when travelling across dimensions

### ISSUE THREAD

**Issue by Master-64** [Globox1997/LevelZ#212]
This bug already exists with the experience bar, and as expected, the bug also occurs for this mod. A very simple fix is to simply update/refresh the LevelZ data on each dimension change. The console command "/playerstats @p add points 0" appears to fix this.

Test was done on 1.18.2 on Fabric v0.14.10.

**Comment by Globox1997** [comment]
This is a known issue and happens when the loading time is too long

**Comment by Globox1997** [comment]
Fixed with LangYueMcs PR for 1.19.2
