### ISSUE TITLE
Easy magic incompatibility (seems fixable)

### ISSUE THREAD

**Issue by Bob74** [Globox1997/LevelZ#215]
[Easy Magic](https://www.curseforge.com/minecraft/mc-mods/easy-magic-fabric) also uses **EnchantmentTableBlockMixin** on **onUse** method:  
https://github.com/Fuzss/easymagic/blob/1.19/Common/src/main/java/fuzs/easymagic/mixin/EnchantmentTableBlockMixin.java

When interacting with the enchantment table, it will work even without any skill points (the item still show that it requires skill points on the tooltip).

I don't know if it is a good solution, but I noticed that it works well if I set the injection point reference from **INVOKE** to **HEAD** in your code:
https://github.com/Globox1997/LevelZ/blob/1.19/src/main/java/net/levelz/mixin/block/EnchantingTableBlockMixin.java#L26

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/94567c45c79b8e7fb8cbec0dcd47fe94609c687e](https://github.com/Globox1997/LevelZ/commit/94567c45c79b8e7fb8cbec0dcd47fe94609c687e)
