### ISSUE TITLE
Easy magic,easy anvils incompatibility

### ISSUE THREAD

**Issue by 12MBTT** [Globox1997/LevelZ#216]
these mods are incompatible with levelz.
I can get into enchanting table and anvil without needing smithing/alchemy skill level
![2022-12-01_12 52 32](https://user-images.githubusercontent.com/117925144/205084044-cffc7cde-9c1b-448d-be63-893ba0fd3ba2.png)
![2022-12-01_12 52 35](https://user-images.githubusercontent.com/117925144/205084060-ccaa1202-8cf0-4e19-941b-df56fb8afb5d.png)
![2022-12-01_12 52 38](https://user-images.githubusercontent.com/117925144/205084069-4726992b-1e99-48d1-867a-8791f69608a6.png)
[latest.log](https://github.com/Globox1997/LevelZ/files/10133371/latest.log)

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/LevelZ/commit/db4f38bc09a9ebe964d2face2993f8b3bbda44eb](https://github.com/Globox1997/LevelZ/commit/db4f38bc09a9ebe964d2face2993f8b3bbda44eb)
