### ISSUE TITLE
Crash on leveling farming.

### ISSUE THREAD

**Issue by Keoxxa** [Globox1997/LevelZ#218]
Had a crash just from trying to level farming. On clicking the game froze before I could release the button and then crashed.
I was level 1, moving to 2 in a rather new world.
Relogging the level did go through, at least.
Leveling up again, it still crashes on clicking farming. Does go through though. So basically I'm crashing every time I level farming.
This world was made shortly before updating levelz from the second latest version to the latest version, with no playtime beforehand.

https://pastebin.com/PeWDFXEe
Crashlog

https://pastebin.com/BEL7Ziz1
Log file.

**Comment by Moirstral** [comment]
This PR will fix the problem, you can roll back to 1.4.1 first, or use my forked version to build it yourself.
https://github.com/Globox1997/LevelZ/pull/220
