### ISSUE TITLE
game crashes on death!

### ISSUE THREAD

**Issue by shupliance** [Globox1997/LevelZ#219]
my game is very stable and everything is quite smooth, but when I die, the game stalls for a long time and closes. i've been trying to isolate the cause within levelz, as the crashlog did specify it originates from some other mod requesting data from levelz. I installed levelz compatibility, not necessarily expecting it to fix the issue, and it continues to happen. this is the log from the most recent crash:
https://pastebin.com/iMKFTKYE
I suspect no other mod in particular, but I reckon it's a compatibility issue as I have many installed. thank you for your help!

**Comment by Moirstral** [comment]
Same as this issue https://github.com/B1n-ry/Youre-in-grave-danger/issues/88

**Comment by shupliance** [comment]
oh thank you, didn't even think to look in other mod's githubs when I saw "levelz" more than once in the log

**Comment by Moirstral** [comment]
The 1.4.2 version of levelz should not have this problem, although 1.4.2 has other problems.
