### ISSUE TITLE
Incompatibility with Tax Free Levels

### ISSUE THREAD

**Issue by ConqAra** [Globox1997/LevelZ#22]
Crashes on launch with tax free levels

[Tax Free Levels](https://www.curseforge.com/minecraft/mc-mods/tax-free-levels)

**Comment by Globox1997** [comment]
Looks like the tax free level mod uses the same redirect as me:
[https://github.com/Globox1997/LevelZ/blob/master/src/main/java/net/levelz/mixin/misc/AnvilScreenHandlerMixin.java](https://github.com/Globox1997/LevelZ/blob/master/src/main/java/net/levelz/mixin/misc/AnvilScreenHandlerMixin.java)
I don't plan to add compatibility but if you play with LevelZ you don't need this mod

**Comment by Ike-l** [comment]
> Looks like the tax free level mod uses the same redirect as me:
> https://github.com/Globox1997/LevelZ/blob/master/src/main/java/net/levelz/mixin/misc/AnvilScreenHandlerMixin.java
> I don't plan to add compatibility but if you play with LevelZ you don't need this mod

what do you mean? does this mod add the same functionality as tax free levels?

**Comment by red2blue** [comment]
> 
> 
> > Looks like the tax free level mod uses the same redirect as me:
> > https://github.com/Globox1997/LevelZ/blob/master/src/main/java/net/levelz/mixin/misc/AnvilScreenHandlerMixin.java
> > I don't plan to add compatibility but if you play with LevelZ you don't need this mod
> 
> what do you mean? does this mod add the same functionality as tax free levels?

Yes, that is what he is saying. Tax Free Levels does the same thing that LevelZ offers.

**Comment by Globox1997** [comment]
it is not exactly the same function but very similar.

**Comment by Globox1997** [comment]
Closing this, refer to [https://github.com/Globox1997/LevelZ/issues/60](https://github.com/Globox1997/LevelZ/issues/60)
