### ISSUE TITLE
changing Player level or points with /playerstats results in error

### ISSUE THREAD

**Issue by ghost** [Globox1997/LevelZ#221]
Hi 
i tried to change my player level with the console command but i got an error saying "An unexpected error occurred trying to execute that command"

in fact every command that tries to interact with "points" or "level" leads to this error. 
all the other stats works just fine.

[15:29:45] [Server thread/INFO]: <--[HERE]
/playerstats Sir_Leroy set level 176
[15:30:41] [Server thread/INFO]: An unexpected error occurred trying to execute that command
/playerstats Sir_Leroy set agility 19
[15:31:16] [Server thread/INFO]: Sir_Leroy stats got changed

i use
levelz 1.4.2
jobsaddon 1.0.6
fabric loader 0.14.10
fabric api 0.68.0
cloth-config 8.2.88-fabric

**Comment by Globox1997** [comment]
Will be fixed with the coming update :)
