### ISSUE TITLE
Levelz doesn't show to be unlocked tools correctly

### ISSUE THREAD

**Issue by TobiPeterG** [Globox1997/LevelZ#23]
Hey there,

Levelz shows instead of e.g. stone pickaxe just "tool tool" when investigating the mining skill, happens with farming as well, but there "axe axe" is shown.
I use the latest version, 1.0.6

**Comment by Globox1997** [comment]
Do you use the latest levelz mod version?

**Comment by TobiPeterG** [comment]
> 
> 
> Do you use the latest levelz mod version?

Yes, here's a screenshot

![grafik](https://user-images.githubusercontent.com/19935382/132881580-52afdd5f-54c7-4fac-8ff5-5a04a1efa13f.png)

happens in a singleplayer world

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/LevelZ/commit/613b23210bcd26506c33b375749d887f43d4dd79](https://github.com/Globox1997/LevelZ/commit/613b23210bcd26506c33b375749d887f43d4dd79)
