### ISSUE TITLE
Pls, protect playerdata server-side. Hackers can change their stats easily

### ISSUE THREAD

**Issue by yetbad** [Globox1997/LevelZ#235]
Pls, move all player data to server-side. Hackers can change their skills easily with Cheat Engine

**Comment by Globox1997** [comment]
Moved to server side with [https://github.com/Globox1997/LevelZ/commit/abeccce2c881af04b6298d9d386479425f99ae16](https://github.com/Globox1997/LevelZ/commit/abeccce2c881af04b6298d9d386479425f99ae16)
