### ISSUE TITLE
Required: True/False key in json

### ISSUE THREAD

**Issue by Sweenus** [Globox1997/LevelZ#237]
Hey there,

Would it be possible to include a "required" key to the json, similar to the "required" key in tag files.

For example, I'm working on adding LevelZ support to Simply Swords and I'm running into an issue where, for each of my modcompat items (MythicMetals/Gobber), levelZ spams the logs with the warning message `LOGGER.info("Resource {} was not loaded cause {} is not a valid item identifier", id.toString(), data.get("item").getAsString());` found at line 134 of the LevelLoader class.

Ideally, I could mark those json files as "required": false, and have the logger ignore them and not spit out a warning when those mods are not installed.

Hope this makes sense!

**Comment by Globox1997** [comment]
Made sense :)
