### ISSUE TITLE
Disable Rare Candies?

### ISSUE THREAD

**Issue by DistantDig** [Globox1997/LevelZ#240]
I might just be blind when searching the config, but I cant seem to find a way to disable the rare candies from dropping. Im making a modpack and it the goal is to only acquire rare candies from quests rather than from mob drops. If its not already there, having a config option to disable rare candy drops would be nice

**Comment by Globox1997** [comment]
Mobs can not drop rare candies by levelz. You might installed a mod which adds custom drops to mobs

**Comment by DistantDig** [comment]
Oh! Thank you so much and sorry for the mistake. Ill go ahead and close this issue then
