### ISSUE TITLE
[Bug] Custom Item Pickaxe - still drop mined block when not that level

### ISSUE THREAD

**Issue by xR4YM0ND** [Globox1997/LevelZ#241]
[Video](https://www.youtube.com/watch?v=0f8YChDsKOQ)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/a987db8a4df07fb3d58eacaa0c49b435c2fcec5b](https://github.com/Globox1997/LevelZ/commit/a987db8a4df07fb3d58eacaa0c49b435c2fcec5b)
