### ISSUE TITLE
[Suggestion] Add more advancements criteria trigger

### ISSUE THREAD

**Issue by AriesStar1337** [Globox1997/LevelZ#244]
Add more trigger that check level for every stats from /playerstats
this will make this mod more customizable and compatible with other mods. E.g. KubeJS

levelz:health
levelz:strength
levelz:agility
...
levelz:experience
levelz:points

Also change levelz:level_up to levelz:level

**Comment by Globox1997** [comment]
Thanks for the suggestion, added with [https://github.com/Globox1997/LevelZ/commit/6cf5f729838736a75643b4ba814df92310bb76ff](https://github.com/Globox1997/LevelZ/commit/6cf5f729838736a75643b4ba814df92310bb76ff)
