### ISSUE TITLE
/playerstats command required permission level is too high

### ISSUE THREAD

**Issue by apace100** [Globox1997/LevelZ#249]
Currently the `playerstats` command introduced by LevelZ requires a permission level of 3.
As it is a game-changing "cheat" command, it should have a permission level of 2.

Permission level 3 is more appropriate for administrative commands like `kick`, `ban` or `whitelist` - vanilla's "cheat" commands are all permission level 2.

You can check [the Minecraft wiki](https://minecraft.fandom.com/wiki/Commands) for an overview of vanilla commands and their permission level as reference.

**Comment by Globox1997** [comment]
Changed to permission level 2 with [https://github.com/Globox1997/LevelZ/commit/934f0bda8ed38b98f6131b1d71c50cb06633bb17](https://github.com/Globox1997/LevelZ/commit/934f0bda8ed38b98f6131b1d71c50cb06633bb17)
