### ISSUE TITLE
[bug?] TESTXX in server console

### ISSUE THREAD

**Issue by TobiPeterG** [Globox1997/LevelZ#25]
Hey there,

after installing this mod, I noticed that sometimes the console shows a TEST30 TEST33, etc. message.
Could it be that some test messages haven't been disabled? :P
(though I have a lot of other mods installed and one of them could be causing it as well)

**Comment by Globox1997** [comment]
It is probably not by levelz but when exactly does it happen?^^

**Comment by TobiPeterG** [comment]
It really probably isn't, it happened when I was in a snow temple. Nothing special really and it didn't just there happen, it happened before as well, without me noticing (just saw it in the log file afterwards)

I'll close this issue as it's not related to levelz, I wish there was just some indication which mod is writing to the console -_-
