### ISSUE TITLE
trinkets and levelz not working correctly together

### ISSUE THREAD

**Issue by Salikuuz** [Globox1997/LevelZ#252]
If i try to equip an item from the Artifacts mod by my hand and the level restriction it like 13 alchemy but i dont have reached that level than it doesn't equip it how it should. but if i try to equip it through my inventory it still equips it even though it has a restriction.

levelz version 1.4.5 1.19.2
trinkets version 3.4.2 1.19.2 
artifacts version  7.1.1 1.19.2

**Comment by Hazender** [comment]
the same on my side with the mermod mod and its necklace. the right click has the restriction but not the drag and drop of the inventory

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/1655539ab155a38562831ec7836bbad1baac7aca](https://github.com/Globox1997/LevelZ/commit/1655539ab155a38562831ec7836bbad1baac7aca)
