### ISSUE TITLE
cloth-api2 is missing

### ISSUE THREAD

**Issue by TylerPickens1** [Globox1997/LevelZ#254]
I am trying to install levelz 1.4.5, but i keep getting the error that I need cloth-api2. I've searched and searched and searched and I cannot find anything called cloth-api2 anywhere. Plz help

**Comment by Globox1997** [comment]
You need the fabric version of this [https://www.curseforge.com/minecraft/mc-mods/cloth-config](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
