### ISSUE TITLE
[Crash] World crashes when thrown entity from Medieval Weapons Mod collides with an Entity

### ISSUE THREAD

**Issue by QuackingDuckz** [Globox1997/LevelZ#256]
Hey, I was using LevelZ in 1.19.2 on Fabric along with the Medieval Weapons Mod, but any time you try to throw a javelin or francisca, the game crashes. I'm pretty sure it is because LevelZ doesn't recognize those items, but I know pretty much nothing about coding, so I haven't been able to figure out it how to fix it in the .jar files.

I have included both the crash report from using a francisca and a Javelin

Any chance I could get some help with it?
[crash-2023-03-09_12.04.48-server francisca.txt](https://github.com/Globox1997/LevelZ/files/10935621/crash-2023-03-09_12.04.48-server.francisca.txt)
[crash-2023-03-09_12.07.45-server javelin.txt](https://github.com/Globox1997/LevelZ/files/10935624/crash-2023-03-09_12.07.45-server.javelin.txt)

Versions of mods used:

LevelZ-Mod-Farbric-1.19.2
medievalweapons-1.4.4
fabric-api-0.62.0+1.19.2
cloth-config-8.2.88-fabric
arrp-0.6.4

**Comment by Globox1997** [comment]
Update levelz to the latest version.
