### ISSUE TITLE
[Compat] RPG difficulty & Traveller's Titles

### ISSUE THREAD

**Issue by CasualJeremy** [Globox1997/LevelZ#257]
Kinda just copied this from Discord by request

Traveler's Titles is used to display biome changes when exploring, if possible it would be cool if it could also display the level of the mobs in the area?

https://www.curseforge.com/minecraft/mc-mods/travelers-titles-fabric

**Comment by Globox1997** [comment]
Please open this issue at the nameplate repository. Levelz doesn't add levels to mobs nor does it change the strength of mobs.
RpgDifficulty doesn't add levels to mobs either, it just strengthen them.
