### ISSUE TITLE
Vanilla Hammer restrictions

### ISSUE THREAD

**Issue by CasualJeremy** [Globox1997/LevelZ#258]
Hammers from the Vanilla Hammers mod are still usable even when the Levelz skill requirement is not met. In addition the hammers do not lose durability when the level hasn't been met

**Comment by Globox1997** [comment]
Added compat with [https://github.com/Globox1997/LevelZ/commit/52758df08a90d02df463872344cb5271637e8c9a](https://github.com/Globox1997/LevelZ/commit/52758df08a90d02df463872344cb5271637e8c9a)
