### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by AngelNuke** [Globox1997/LevelZ#259]
Hi, I have a server with several mods and one of them, clearly, is LevelZ (I also have the jobs addon). The thing is that my friends and I were playing without problems until 2 of my friends were biting the Sculk block and the server crashed and closed instantly. Looking at why it crashed I saw that it was the fault of the levelz mod. It seems that it gives some bug when breaking in that block and the console gets full of warnings when breaking the Sculk block.

The report is as follows: 

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2023-04-03 02:14:29
Description: Ticking entity

java.lang.IndexOutOfBoundsException: Index (0) is greater than or equal to list size (0)
	at it.unimi.dsi.fastutil.objects.ObjectArrayList.get(ObjectArrayList.java:411)
	at net.minecraft.class_2248.handler$bjd000$levelz$getDroppedStacksMixin(class_2248.java:2741)
	at net.minecraft.class_2248.method_9609(class_2248.java:339)
	at net.minecraft.class_2248.method_9511(class_2248.java:365)
	at net.minecraft.class_2248.method_9556(class_2248.java:444)
	at net.minecraft.class_3225.method_14266(class_3225.java:275)
	at net.minecraft.class_3225.method_14264(class_3225.java:106)
	at net.minecraft.class_3222.method_5773(class_3222.java:443)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at it.unimi.dsi.fastutil.objects.ObjectArrayList.get(ObjectArrayList.java:411)
	at net.minecraft.class_2248.handler$bjd000$levelz$getDroppedStacksMixin(class_2248.java:2741)
	at net.minecraft.class_2248.method_9609(class_2248.java:339)
	at net.minecraft.class_2248.method_9511(class_2248.java:365)
	at net.minecraft.class_2248.method_9556(class_2248.java:444)
	at net.minecraft.class_3225.method_14266(class_3225.java:275)
	at net.minecraft.class_3225.method_14264(class_3225.java:106)
	at net.minecraft.class_3222.method_5773(class_3222.java:443)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 397
	Entity Name: iGhost98
	Entity's Exact location: -1190.77, -49.00, -752.78
	Entity's Block location: World: (-1191,-49,-753), Section: (at 9,15,15 in -75,-4,-48; chunk contains blocks -1200,-64,-768 to -1185,319,-753), Region: (-3,-2; contains chunks -96,-64 to -65,-33, blocks -1536,-64,-1024 to -1025,319,-513)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 3 total; [class_3222['AngelNuke'/78, l='ServerLevel[world]', x=-1276.68, y=82.00, z=-597.39], class_3222['iGhost98'/397, l='ServerLevel[world]', x=-1190.77, y=-49.00, z=-752.78], class_3222['Sir_Toro'/653, l='ServerLevel[world]', x=-1124.07, y=63.00, z=-622.01]]
	Chunk stats: 5258
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,68,0), Section: (at 0,4,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2887787 game time, 3650879 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 31782 (now: false), thunder time: 70529 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.15.0-60-generic
	Java Version: 17.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1824767392 bytes (1740 MiB) / 2879389696 bytes (2746 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 3
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7351P 16-Core Processor
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 2
	Microarchitecture: Zen
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 98184.31
	Virtual memory used (MB): 85935.55
	Swap memory total (MB): 33791.99
	Swap memory used (MB): 4178.13
	JVM Flags: 3 total; -Xms1024M -Xmx3072M -XX:-UsePerfData
	Fabric Mods: 
		adventurez: AdventureZ 1.4.17
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.5.69
		bclib: BCLib 2.1.6
		betteradvancements: Better Advancements 0.2.2.142
		bettercombat: Better Combat 1.6.2+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.2
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.4
		betterfortresses: YUNG's Better Nether Fortresses 1.19.2-Fabric-1.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betternether: Better Nether 7.1.3
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		biomemakeover: Biome Makeover 1.19.2-1.6.2
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.6-1.19.2
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		customizableelytra: Customizable Elytra 1.6.4-1.19
		dataattributes: Data Attributes 1.4.2
		deeperdarker: Deeper and Darker 1.1.6
			customportalapi: Custom Portal Api 0.0.1-beta54-1.19
			paragon: Paragon 3.0.2
				blue_endless_jankson: jankson 1.2.1
				com_moandjiezana_toml_toml4j: toml4j 0.7.2
				org_yaml_snakeyaml: snakeyaml 1.27
		dummmmmmy: MmmMmmMmmMmm 1.19.2-1.7.1
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.2+kotlin.1.8.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.18
		forgeconfigapiport: Forge Config API Port 4.2.11
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		iceberg: Iceberg 1.0.46
		jade: Jade 8.7.3
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.6.0.1013
		jobsaddon: JobsAddon 1.0.11
		journeymap: Journeymap 5.9.4
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		levelz: LevelZ 1.4.7
			libgui: LibGui 6.0.1+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		libz: LibZ 1.0.0
		lithium: Lithium 0.11.1
		minecraft: Minecraft 1.19.2
		mobscarecrow: Mob Scarecrow 2.2.1-1.19.1
		moonlight: Moonlight 1.19.2-2.2.27
		moremobvariants: More Mob Variants 1.0.1
		naturescompass: Nature's Compass 1.19.2-2.1.0-fabric
		nyfsquiver: Nyf's Quivers Fabric-0.5.1-1.19.2
			trinkets: Trinkets 3.5.0
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		phosphor: Phosphor 0.8.1
		player-animator: Player Animator 1.0.2
		resourcefulconfig: Resourcefulconfig 1.0.20
		rottencreatures: Rotten Creatures 1.0.1
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		simple_backpack: SimpleBackpack 1.3.25
		simplyswords: Simply Swords 1.43.1-1.19.2
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		spiderstpo: Spiders 2.0 1.19.2-2.0.3
		t_and_t: Towns and Towers 1.9
		tempad: Tempad 1.4.3
			team_reborn_energy: Energy 2.2.0
		voidz: VoidZ 1.0.9
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.9
			org_javassist_javassist: javassist 3.28.0-GA
	Server Running: true
	Player Count: 3 / 10; [class_3222['AngelNuke'/78, l='ServerLevel[world]', x=-1276.68, y=82.00, z=-597.39], class_3222['iGhost98'/397, l='ServerLevel[world]', x=-1190.77, y=-49.00, z=-752.78], class_3222['Sir_Toro'/653, l='ServerLevel[world]', x=-1124.07, y=63.00, z=-622.01]]
	Data Packs: vanilla, Fabric Mods, file/afk display v1.1.3.zip (incompatible), file/awesome_dungeon_1.19.2+3.1.0.zip, file/confetti creepers v2.2.3.zip (incompatible), file/double shulker shells v1.3.3.zip (incompatible), file/elevators v1.0.4.zip (incompatible), file/fast leaf decay v2.0.6.zip (incompatible), file/graves v2.8.7.zip (incompatible), file/larger phantoms v1.2.4.zip (incompatible), file/more mob heads v2.11.1.zip (incompatible), file/multiplayer sleep v2.6.3.zip (incompatible), file/name colors v1.0.1.zip (incompatible), file/player head drops v1.1.3.zip (incompatible), file/timber v2.1.5.zip (incompatible)
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/LevelZ/commit/f5b39355474b3ef68418b0910003d6882881ec66](https://github.com/Globox1997/LevelZ/commit/f5b39355474b3ef68418b0910003d6882881ec66)
