### ISSUE TITLE
[Feature Request] entity rideable second slot - works when first slot is used

### ISSUE THREAD

**Issue by xR4YM0ND** [Globox1997/LevelZ#260]
So basically any player can hop in the second slot boat _(or modded ships or so / anything with more seats)_
when a player is already sitting in the first slot (player needs to be the level defined to use the first slot for an entitiy)

then the others can jump in and out from the second seat without the required level

When the contorl person ( first seat ) ejects , the others should get ejected as well ( only the players who dont have the required level to use this entitiy )

~ Idea by CasualJeremy#4956

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/LevelZ/commit/b7a64d4ec6ed25f71501ce35e9343b471550073e](https://github.com/Globox1997/LevelZ/commit/b7a64d4ec6ed25f71501ce35e9343b471550073e)
