### ISSUE TITLE
Is there a way to make items from other mods like armor and tools locked until a specific level is reached?

### ISSUE THREAD

**Issue by ChaosMakerMLG** [Globox1997/LevelZ#262]
Im making private modpack for fabric and im using a few mods that add weapons and armor. And i was wondering if i could somehow make levelz lock usage of these moded items until player levels up. Its for version 1.19.2 and im using better nether, mod better end mod, deeper darker mod and medival weapons mod, obviously theres ton of mods more but i just listed the ones that add armor, tools and weapons. Also im using no punching trees mod and levelz doesnt let me break tall grass with flint knife cause it thinks its a weapon, than theres a problem where players cant get sticks from leaves because it doesnt drop any. I woould be very greatful if someone helped me with that, I dont know much javascript but if its required to make the issues go away and getting the things i need to work than ill learn it.

**Comment by Globox1997** [comment]
Check out my discord and ask Ray for help :)
