### ISSUE TITLE
[Crash]: Crashing when opening the game

### ISSUE THREAD

**Issue by Gaisrick** [Globox1997/LevelZ#267]
### Minecraft Version

1.19.x

### Mod Loader Version

1.19.2

### Mod Version

1.4.8

### Describe the Issue

Don't know what is the problem, but your mod conflicts with other mods. I know, this is not your problem, but at least, inform us about the incompatible ones if you know. Also, JobsAddon is incompatible with others too, if that's helpful. thanks for your hard free work.

### latest.log

[crash-2023-05-04_16.23.27-client.txt](https://github.com/Globox1997/LevelZ/files/11398010/crash-2023-05-04_16.23.27-client.txt)

### Do you use any other mods except the required ones?

yes, and the mod doesn't have any problem when the others are disabled

**Comment by Globox1997** [comment]
Do you use the latest inmisaddon and levelz version?

**Comment by xR4YM0ND** [comment]
Use latest, should work there.

If not, open a new issue pls
