### ISSUE TITLE
[bug?] Leveling up alchemy hurts?

### ISSUE THREAD

**Issue by noncom** [Globox1997/LevelZ#27]
When I level up alchemy it makes me hurt approx 1 time in 5-7 seconds until I have approx 40-45% of HP left and periodically applies to me 1-second fleeting Haste II and Strength effects. Also sometimes I set things on fire now. I see the regular hurting "screenshake" animation even when I enter spectator mode. I have tried removing my alchemy levels with NBT editor and it stops that weird behavior. Adding the points back resumes it.

This totally looks like a bug, does it? If it's the expected behavior then I can't find any mention that it should work like this.

Checked both in singleplayer and multiplayer.

I'm playing a slightly modified Medieval Minecraft 15.5 where I've added AppleSkin and Enchantment Descriptions and replaced PlayerEx back again with LevelZ. I've attached the server logfile to show what mods are in. The "bug" itself leaves no trace in the log though.

[latest.log](https://github.com/Globox1997/LevelZ/files/7150382/latest.log)

**Comment by Globox1997** [comment]
Moving to [https://github.com/Globox1997/LevelZ/issues/29](https://github.com/Globox1997/LevelZ/issues/29)
