### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by Nude-Zenpai** [Globox1997/LevelZ#282]
### Make sure you are not opening a duplicate.

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

1.2.1 compatibility please?

**Comment by night2078** [comment]
You can do that very easily for yourself.

open the levelz.jar with 7zip or winrar
pull out the fabric.mod.json file
open it with text editor
search for the "minecraft" line under the "depends" categorie
just replace the "1.20" with "1.20.1"
delete the existing fabric.mod.json in the jar and replace it with your edited one.
finished, it should work just fine now, that's what i did atleast and its working fine.

**Comment by Eagllus** [comment]
I compiled the Jar file for anyone waiting.
Since GitHub doesn't support jar files directly it's a zip, unpack it any place it in your mod folder.

[levelz-1.4.9.jar.zip](https://github.com/Globox1997/LevelZ/files/12079437/levelz-1.4.9.jar.zip)
