### ISSUE TITLE
No xp from Mobs at mob spawner

### ISSUE THREAD

**Issue by Enikimm** [Globox1997/LevelZ#283]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.21

### Mod Version

1.4.9

### Describe the Issue

The mobs wont give xp upon killing mobs that spawn from spawner after a killing a few handfuls. 
I'm not sure whats wrong here but that is what I have experienced and would like it to be fixed

### latest.log

[latest.log](https://github.com/Globox1997/LevelZ/files/11900767/latest.log)

### Do you use any other mods except the required ones?

_Yes_

**Comment by xR4YM0ND** [comment]
You can change this via config
```json
"disableMobFarms": false,
```

**Comment by xR4YM0ND** [comment]
Pls open a new issue if this option doesnt fix it
