### ISSUE TITLE
xp bug with Create mod

### ISSUE THREAD

**Issue by amatorius36** [Globox1997/LevelZ#287]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.21

### Mod Version

1.4.9

### Describe the Issue

Hello.
I have a server with Levelz 1.4.9 and Create 0.5.1b
Any ore that is locked gives me normal xp and xp from Levelz.
This error only appears when I have the Create mod on the server, when I remove Create, Levelz works correctly.
The same thing happens in SP.

I have tried different versions of Levelz and Create, the problem persists

### latest.log

[latest.log](https://github.com/Globox1997/LevelZ/files/12098678/latest.log)

**Comment by Globox1997** [comment]
Out of time reasons I only work on the latest version of my mods, if this still persist in the latest version, reopen this issue and hit me up in discord.
