### ISSUE TITLE
Levelz not running on dedicated server

### ISSUE THREAD

**Issue by Vathen12** [Globox1997/LevelZ#291]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.21

### Mod Version

levelz-1.4.10.jar

### Describe the Issue

When Levelz is activated/installed on my Windows Dedicated Server I get the following error. (Log will follow.)

Connection Lost!
Internal Exception:
io.netty.handler.codec.DecoderException:
java.lang.IndexOutOfBoundsException: readerIndex(3) +
length(1) exceeds writerIndex(3): 
PooledUnsafeDirectByteBuf(ridx: 3, widx: 3, cap: 3)

Note: 
I have tried this as the only mod running and I still get same error. So it is not a conflict. 
I also run the JobsAddon. 

Log: 
My log will include additional mods. But again, the problem still happens when it is the only mod loaded. 

### latest.log

2023-08-05 21:24:47,895 (INFO) [UI][12476] AppCenter - 

<------------------------------+ 0.228.0.21 +-------------------------------->

### Do you use any other mods except the required ones?

I do, but have tested with all other mods disabled. Problem still exists.

______________________________________________

Resolved!!!! 

My loader app kept missing a file AND loading the wrong one. 
Easiest solution - manually download and app the apps to the server.

**Comment by Vathen12** [comment]
Resolved!!!!

My loader app kept missing a file AND loading the wrong one.
Easiest solution - manually download and app the apps to the server.

**Comment by Globox1997** [comment]
Awesome :)
