### ISSUE TITLE
Wither doesnt spawn with mod

### ISSUE THREAD

**Issue by javeoff** [Globox1997/LevelZ#294]
### Minecraft Version

1.18.x

### Mod Loader Version

api 0.76.0

### Mod Version

1.3.3

### Describe the Issue

If i remove mod, wither spawns in the world. I tried to set full all levels, but it doesnt work :(

### latest.log

no error

**Comment by Globox1997** [comment]
Out of time reasons I only work on the latest version. Reopen if still happening in latest version.
