### ISSUE TITLE
Mixin Application Failure during preLaunch for 'altorigingui'

### ISSUE THREAD

**Issue by cyancccc** [Globox1997/LevelZ#299]
### Minecraft Version

1.20.x

### Mod Loader Version

fabric-loader-1.20.1

### Mod Version

levelz-1.4.10

### Describe the Issue

Description:

While attempting to launch Minecraft with the 'altorigingui' mod and 'levelz' mod installed, the game crashes during the preLaunch stage. A review of the crash logs suggests a mixin application failure related to the 'levelz' mod.

Details:

Primary Error: The game fails to execute the preLaunch entrypoint due to errors provided by the 'altorigingui' mod.

Mixin Details: The mixin in question belongs to the 'levelz' mod. The specific mixin that failed is levelz.mixins.json:compat.ChopResultMixin.

Technical Details: The crash report indicates a "@Mixin target type mismatch" error. The mixin targets ht.treechop.common.chop.ChopResult. There seems to be a type discrepancy, with the target (ChopResult) being an interface, but the mixin might have expected a different type.

Additional Information:

I've ensured that all other mods and Fabric itself are up-to-date. The issue seems to persist specifically with the combination of 'altorigingui' and 'levelz'.

### latest.log

[2023-08-25-7.log.gz](https://github.com/Globox1997/LevelZ/files/12436897/2023-08-25-7.log.gz)

**Comment by xR4YM0ND** [comment]
Should be fixed in 1.4.11

Pls open a new issue if this still exists
