### ISSUE TITLE
Alchemy bug

### ISSUE THREAD

**Issue by BenZZZin** [Globox1997/LevelZ#3]
I have an issue with leveling up alchemy stats. For some reason, when i add a point in alchemy, it basically breaks my character by changing hp, attack and movement stats repeatedly. You can check a GIF-file. What could cause the problem? Other stats has no such influence.
![TdCAYOjci6](https://user-images.githubusercontent.com/89310332/130326907-e7b73435-72eb-4819-b60a-2053e0b1d79d.gif)

**Comment by Globox1997** [comment]
I guess you filled yourself up with too much benzzzzzzin xD 
Super weird bug o-o looks like a bug in the matrix
Does it happen if you have levelz only installed?

**Comment by BenZZZin** [comment]
haha, yeah, totally filled up xD
Well, initially i thought i ran clean minecraft with fabric + this mod. Turned out i didn't)) I had a whole bunch of mods xD Well, from here it was easy enough - I checked every mod and the one that caused this bug was "Extra Enchants" (https://github.com/herb-mc/extra_enchants) 
Thanks for your reply anyway)) Great mod)

**Comment by Globox1997** [comment]
extra enchants has a lot of mixins and I don't have a plan what could cause such trouble, will be a unsolved incompat.
Thank you too :)
