### ISSUE TITLE
"Trade" makes prices go down by 20% per point (?)

### ISSUE THREAD

**Issue by Vaelisious** [Globox1997/LevelZ#30]
Tach. Ich dacht' ich mach das hier mal auf die schnelle Art und Weise.

Ich habe in meiner momentanen 1.17.1 Welt ein paar Villager erstellt und momentan 1/20 Punkten in "Trade" um
Trading zu ermöglichen. Preise von NPC's sind um ca. 20% reduziert. In der Beschreibung heißt es das Preise pro Skillpunkt um 0.2 reduziert werden. Ich denke mal, es sollte 0.02 sein (selbst das wäre ziemlich broken = 40%.)

Vorschlag: Value 0.01 wäre wohl am "fairsten" (Hero of the Village gibt bei Rank 1 -> 30% + 6.25% pro weiteres Level.). Heißt: 20 Skillpunkte = 20% Discount?

Ich habe es jetzt noch nicht weiter getestet, aber ich denke wenn ich 5 Skillpunkte in Trade habe, sind Preise um 100% (bzw. 99%) reduziert und jeder Trade wäre quasi 1 zu 1, was komplett Gamebreaking ist.

Sollte ich mich irren und weiters herausfinden, werd' ich mich melden.
- Vael
PS: Ich konnte deinen/euren Discord nicht finden sonst hätte ich mich dort gemeldet.

**Comment by Globox1997** [comment]
Jo das ist seltsam, dankeschonmal für die info.

**Comment by Globox1997** [comment]
Overhauled the price system, so it should be fixed with [https://github.com/Globox1997/LevelZ/commit/054d43a245a2c371a740a5ce034799a242a0a492](https://github.com/Globox1997/LevelZ/commit/054d43a245a2c371a740a5ce034799a242a0a492)
