### ISSUE TITLE
[Crash] With latest HT Tree Chop 0.18.3

### ISSUE THREAD

**Issue by xR4YM0ND** [Globox1997/LevelZ#304]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.22

### Mod Version

0.14.10

### Describe the Issue

Instant crash

just these 2 mods

### latest.log

https://gist.github.com/xR4YM0ND/6f0bd96ae828ccb422573453310a4a00

**Comment by MbtMarco** [comment]
**I can confirm that:**
https://mclo.gs/a4Ue0OE

**Comment by arctlw** [comment]
Can also confirm this

**Comment by xR4YM0ND** [comment]
Should be fixed in 1.4.11

Pls open a new issue if this bug still exists
