### ISSUE TITLE
Exp Stops Dropping/

### ISSUE THREAD

**Issue by IcyMoon999** [Globox1997/LevelZ#312]
### Minecraft Version

1.20.x

### Mod Loader Version

1.20.0

### Mod Version

1.20.1

### Describe the Issue

I made a skelly spawner farm for exp but every couple of kills exp and loot stop dropping completely. idk if that is on purpouse but yeah. 

### latest.log

Im new to computer stuff and files.

### Do you use any other mods except the required ones?

no

**Comment by IcyMoon999** [comment]
- [ ]

**Comment by Adam1609** [comment]
Did you turn on disableMobFarm on the config folder? Because that function won't allow monster spawning from the spawner dropping experience.

**Comment by IcyMoon999** [comment]
No But I don't know how but i'll figure it out

**Comment by Globox1997** [comment]
It's enabled by default since the mod does not make sense with xp farms.
Still you can turn it off

**Comment by IcyMoon999** [comment]
I bought this pc a month ago. I really don't understand how to turn it off.

**Comment by IcyMoon999** [comment]
I figuerd it out
