### ISSUE TITLE
Can't break gravel

### ISSUE THREAD

**Issue by morceaudebois** [Globox1997/LevelZ#314]
### Minecraft Version

1.20.x

### Mod Loader Version

latest

### Mod Version

latest

### Describe the Issue

Hi! I'm making a private modpack with both LevelZ and [No Tree Punching](https://modrinth.com/mod/no-tree-punching) installed. 

With No Tree Punching, you need to mine gravel before doing anything in the game, it's a problem since LevelZ prevents you to do so until you're level 1 in mining.

I expected to see a rule in the config file for it but it doesn't seem to exist. Is there something I could do about it?
Thank you!

**Comment by Samn100** [comment]
I would need some config for these two mods too.

**Comment by Globox1997** [comment]
Check out the readme.
