### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by GitUser14975** [Globox1997/LevelZ#320]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.23

### Mod Version

1.4.11+1.20.1

### Describe the Issue

Hi, someone had problems with my modpack most likely related to LevelZ. When they tried to craft a pickaxe, or grab any tool, the game crashed for them. It seems that interacting with anything that is related to levels crashes the game for them. I don't experience the bug myself, so I don't know why it happens for them. They have sent me their logs, I hope that's enough information. Could be some mod incompatibility, but again, this doesn't happen for me and only for that one player.

### latest.log

https://mclo.gs/0YFHn7Y

### Do you use any other mods except the required ones?

Yes

**Comment by Globox1997** [comment]
Add these two jvm flags to your java arguments
-Duser.language=en -Duser.country=US

**Comment by GitUser14975** [comment]
It seems to have fixed the problem for the player, thank you so much!
