### ISSUE TITLE
Clumps support for 1.18 version

### ISSUE THREAD

**Issue by le-off** [Globox1997/LevelZ#327]
### Make sure you are not opening a duplicate.

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

From what I've seen there is Clumps support for version 1.20 and it would be nice to have Clumps support for 1.18 as well since some modpacks run the LevelZ mod on 1.18.

**Comment by Globox1997** [comment]
Out of time reasons I only work on the latest versions of my mods.
