### ISSUE TITLE
Critical mod error [Urgently pay attention]

### ISSUE THREAD

**Issue by Anhelm** [Globox1997/LevelZ#33]
When using a reset potion, the skills are reset to zero, but the parameters remain in place. Thanks to this, players can endlessly raise all the parameters for themselves and become immortal.
![image](https://user-images.githubusercontent.com/74124042/133881763-08a702c7-8814-49b6-9e5e-ac96d7a6ee39.png)

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/LevelZ/commit/9123c46eba7ff3f40fc9e8f20e2acad97620741b](https://github.com/Globox1997/LevelZ/commit/9123c46eba7ff3f40fc9e8f20e2acad97620741b)
