### ISSUE TITLE
new advancement criteria trigger

### ISSUE THREAD

**Issue by MrOz59** [Globox1997/LevelZ#331]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

new advancement criteria trigger for when the player levels up, to facilitate integration with other mods through functions, or for servers to give some bonus or something like that, in my case I wanted to implement a function for simply skills

**Comment by Globox1997** [comment]
What about the datapack section in the Readme? Or what is the difference to the existing ones?

**Comment by MrOz59** [comment]
If I understand the existing ones correctly, it only works for specific levels, so if I wanted to trigger a function or command every time the player levels up I would have to do an advancement for each level, which would be a lot more work and complicated than having a criteria for level up, would make it much easier when making modpack or servers with more customized systems

**Comment by Globox1997** [comment]
I see, when I get back to this mod I will add it

**Comment by Globox1997** [comment]
If you set the level to 0 it will always trigger when the player levels one level up.
Added with [https://github.com/Globox1997/LevelZ/commit/a9b34db442cca521cbab069b7bba2e446c2e93f3](https://github.com/Globox1997/LevelZ/commit/a9b34db442cca521cbab069b7bba2e446c2e93f3)
