### ISSUE TITLE
[BUG]: Armor Restriction Bypass

### ISSUE THREAD

**Issue by xR4YM0ND** [Globox1997/LevelZ#334]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.3

### Mod Version

1.4.12

### Describe the Issue

You can bypass armor restriction if another armor is already in the slot.

Just wear leather armor (have the skill for that) -> take diamond armor and right click on the armor slot.

(BTW left click destroys the item forever)

### latest.log

-

**Comment by Globox1997** [comment]
Does it happen with only levelz installed?

**Comment by xR4YM0ND** [comment]
yes

**Comment by RockZe** [comment]
I confirm! This bug is old and has been observed since version 1.19.2. Now the situation repeats the same way on 1.20.1

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/07902d0c4ee5d56af3c3ac4ca525e96bc00c09bc](https://github.com/Globox1997/LevelZ/commit/07902d0c4ee5d56af3c3ac4ca525e96bc00c09bc)
