### ISSUE TITLE
[Bug]: Tooltip Text not working when REI favorite item is present

### ISSUE THREAD

**Issue by xR4YM0ND** [Globox1997/LevelZ#336]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.3

### Mod Version

1.4.12

### Describe the Issue

![2024-01-05_13 54 55](https://github.com/Globox1997/LevelZ/assets/97298005/98b7a272-e26d-410e-a79c-b346ea04e63a)
![2024-01-05_13 55 43](https://github.com/Globox1997/LevelZ/assets/97298005/84b911c3-41c8-4493-880a-a55a6af8d5fb)

~ You can favorite items in REI while hovering over it and press "A"

### latest.log

-

### Do you use any other mods except the required ones?

Aged 2.1.3_dev

**Comment by xR4YM0ND** [comment]
REI - incompat
Shouldnt be in this screen also

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/d12e3e35b32d711a244740092d660436d4cf17e0](https://github.com/Globox1997/LevelZ/commit/d12e3e35b32d711a244740092d660436d4cf17e0)
