### ISSUE TITLE
LevelZ on servers...

### ISSUE THREAD

**Issue by parkurnic** [Globox1997/LevelZ#35]
There are just tons... tons.  tons.  tons.  tons of bugs when you play with LevelZ on the server. Just try it yourself. It's imposible to play.

**Comment by Globox1997** [comment]
This sounds like mod incompatibilities, I would recommend to deinstall levelz for now.
Appreciate all help I get to figure these bugs out :)

**Comment by Globox1997** [comment]
Reopen with more info, if bugs still exist :)
