### ISSUE TITLE
Error Redstone

### ISSUE THREAD

**Issue by Anhelm** [Globox1997/LevelZ#36]
Does not display a restriction in the redstone fashion.
This causes the client to crash when trying to add redstone to potions.
![image](https://user-images.githubusercontent.com/74124042/134325137-99ffece2-dc59-4770-962a-436317cd03e9.png)
![image](https://user-images.githubusercontent.com/74124042/134325148-5ac17aa5-ea8e-4771-a716-b34351a4b43c.png)
[crash-2021-09-22_11.46.33-client.txt](https://github.com/Globox1997/LevelZ/files/7209768/crash-2021-09-22_11.46.33-client.txt)

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/LevelZ/commit/4aabf83049e1befb4004f170f1f771e13486bb80](https://github.com/Globox1997/LevelZ/commit/4aabf83049e1befb4004f170f1f771e13486bb80)
If it still crashes with the coming update, please reopen this issue with the crash log
