### ISSUE TITLE
issue with new 1.21 version

### ISSUE THREAD

**Issue by beanzzz12** [Globox1997/LevelZ#362]
### Minecraft Version

1.21.x

### Mod Loader Version

1.21

### Mod Version

1.21

### Describe the Issue

To put it shortly the world doesnt save what level im at when i leave. if i use the starting levels, then leave and join back theyre all gone. cheers fix it soon pls

### latest.log

dunno what this means

### Do you use any other mods except the required ones?

yes but the mod works fine, apart from this.

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/026fc2c72dd7f78929d2b924cfeb6edd9471d793](https://github.com/Globox1997/LevelZ/commit/026fc2c72dd7f78929d2b924cfeb6edd9471d793)
Thanks for the info
