### ISSUE TITLE
Issue on 1.21(1.21.1) versions

### ISSUE THREAD

**Issue by PengWanYT** [Globox1997/LevelZ#363]
### Minecraft Version

1.21.x

### Mod Loader Version

1.21.1

### Mod Version

1.21.1

### Describe the Issue

I had a problem with this mod levelz issue, when you had level on game and upgrade, then you leave and join back again,
All of the level is gone, even exp too, idk how I support do with that :(

### latest.log

I don't know, does not show about that

### Do you use any other mods except the required ones?

Well I did add required mod everytime

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/026fc2c72dd7f78929d2b924cfeb6edd9471d793](https://github.com/Globox1997/LevelZ/commit/026fc2c72dd7f78929d2b924cfeb6edd9471d793)
Thanks for the report.
