### ISSUE TITLE
1.21.1 server

### ISSUE THREAD

**Issue by PengWanYT** [Globox1997/LevelZ#364]
### Minecraft Version

1.21.x

### Mod Loader Version

1.21.1

### Mod Version

1.21.1

### Describe the Issue

The server use this mod, let's short chat

Well it's same issue that can't saving level and point skill after you leave and join back again on server
Would you mind fix this? 
Sorry but it's just me play on server alot to found issue,
If you found no issue on mod, that mean my game probably is need re download : (

### latest.log

Don't know, cuz doesn't not show

### Do you use any other mods except the required ones?

I had add required

**Comment by Globox1997** [comment]
Mh there is no 1.21.1 mod version, which mod version do you use?

**Comment by PengWanYT** [comment]
> Mh there is no 1.21.1 mod version, which mod version do you use?

Well I am using levelz mod (1.21.1 mod)
When i am using levelz mod on server, it some reason level will random reset stats when I am setting config,
I am think that kinda my server system problem I guess?

Sorry bother your time by this, me just first time report issue from here.

**Comment by Globox1997** [comment]
You miss understand something. LevelZ has no 1.21.1 mod version.
My guess is you are using 2.0.0 but just update to 2.0.1

**Comment by PengWanYT** [comment]
> You miss understand something. LevelZ has no 1.21.1 mod version. My guess is you are using 2.0.0 but just update to 2.0.1

Oh ya it's 2.0.1 mod, well sorry sir, and ya I am use 2.0.1 but yaa had random reset some reason on server,
Well thx sir, kinda no issue rn. 👐

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/c3f3bec2873b7798396ba3045045eb39c7ea0279](https://github.com/Globox1997/LevelZ/commit/c3f3bec2873b7798396ba3045045eb39c7ea0279)
