### ISSUE TITLE
another issue?

### ISSUE THREAD

**Issue by beanzzz12** [Globox1997/LevelZ#365]
### Minecraft Version

1.21.x

### Mod Loader Version

1.21

### Mod Version

1.21

### Describe the Issue

The leaving and re-joining thing now doesn't delete your level, but now when you die you lose all of your levels? is this a feature of the mod and are you able to change a setting to save your levels or is it a bug? thanks again man.

### latest.log

still dunno what this is

### Do you use any other mods except the required ones?

yes but the mod works fine, apart from this.

**Comment by beanzzz12** [comment]
sorry didnt realise you where able to change the settings lol, works great good mod! only a setting issue if anyone is concerned

**Comment by beanzzz12** [comment]
So. I am still having issues. when i set the mod to not make me lose my skill point progress, and it still makes me lose them when I die. is it because I'm playing in 1.21.1 or because I normally play on hard mode?

EDIT: just tested and even when i have the level reset turned off in the menu i can die once and keep them but i die again and then it resets. I think there could also be a bug where on the first death i keep my levels but my tools dont work anymore despite being a high enough level, not sure on this tho.

**Comment by PengWanYT** [comment]
> So. I am still having issues. when i set the mod to not make me lose my skill point progress, and it still makes me lose them when I die. is it because I'm playing in 1.21.1 or because I normally play on hard mode?
> 
> EDIT: just tested and even when i have the level reset turned off in the menu i can die once and keep them but i die again and then it resets. I think there could also be a bug where on the first death i keep my levels but my tools dont work anymore despite being a high enough level, not sure on this tho.

Same of me, I am already noticed this issue 😭

**Comment by beanzzz12** [comment]
yeah so tested again not sure if you've attempted to fix it but still having the same issue

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/c3f3bec2873b7798396ba3045045eb39c7ea0279](https://github.com/Globox1997/LevelZ/commit/c3f3bec2873b7798396ba3045045eb39c7ea0279)
