### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by Hng-Vit** [Globox1997/LevelZ#366]
### Minecraft Version

1.21.x

### Mod Loader Version

0.16.9

### Mod Version

1.21.1

### Describe the Issue

just crashed multiple times, cannot even move the player before the crashes came.

### latest.log

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-11-27 20:44:26
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.levelz.access.LevelManagerAccess.getLevelManager()" because "playerEntity" is null
	at knot//net.levelz.util.BonusHelper.potionEffectChanceBonus(BonusHelper.java:91)
	at knot//net.minecraft.class_1812.localvar$clh000$levelz$finishUsingMixin(class_1812.java:517)
	at knot//net.minecraft.class_1812.method_57389(class_1812.java)
	at knot//net.minecraft.class_1844.method_57402(class_1844.java:90)
	at knot//net.minecraft.class_1812.method_7861(class_1812.java:54)
	at knot//net.minecraft.class_1799.method_7910(class_1799.java:389)
	at knot//net.minecraft.class_1309.method_6040(class_1309.java:3278)
	at knot//net.minecraft.class_1309.method_37119(class_1309.java:3154)
	at knot//net.minecraft.class_1309.method_6076(class_1309.java:3141)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2469)
	at knot//net.minecraft.class_1308.method_5773(class_1308.java:372)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:770)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:498)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:408)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:372)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at knot//net.levelz.util.BonusHelper.potionEffectChanceBonus(BonusHelper.java:91)
	at knot//net.minecraft.class_1812.localvar$clh000$levelz$finishUsingMixin(class_1812.java:517)
	at knot//net.minecraft.class_1812.method_57389(class_1812.java)
	at knot//net.minecraft.class_1844.method_57402(class_1844.java:90)
	at knot//net.minecraft.class_1812.method_7861(class_1812.java:54)
	at knot//net.minecraft.class_1799.method_7910(class_1799.java:389)
	at knot//net.minecraft.class_1309.method_6040(class_1309.java:3278)
	at knot//net.minecraft.class_1309.method_37119(class_1309.java:3154)
	at knot//net.minecraft.class_1309.method_6076(class_1309.java:3141)
	at knot//net.minecraft.class_1309.method_5773(class_1309.java:2469)
	at knot//net.minecraft.class_1308.method_5773(class_1308.java:372)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:770)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:498)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:408)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)

-- Entity being ticked --
Details:
	Entity Type: minecraft:wandering_trader (net.minecraft.class_3989)
	Entity ID: 152
	Entity Name: Wandering Trader
	Entity's Exact location: -147.35, 65.00, 373.21
	Entity's Block location: World: (-148,65,373), Section: (at 12,1,5 in -10,4,23; chunk contains blocks -160,-64,368 to -145,319,383), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: 0.06, -0.08, -0.04
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:498)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:408)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:372)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Hoang_Tiv1107'/3, l='ServerLevel[27/11/24]', x=-126.70, y=19.00, z=364.70]]
	Chunk stats: 258
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,79,0), Section: (at 0,15,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 120874 game time, 207055 day time
	Level name: 27/11/24
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Commands: false
	Level weather: Rain time: 36257 (now: false), thunder time: 28847 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 269
Stacktrace:
	at knot//net.minecraft.class_3218.method_8538(class_3218.java:1693)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1024)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 248996232 bytes (237 MiB) / 1476395008 bytes (1408 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 11
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1060 3GB
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 3072.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6094
	Memory slot #0 capacity (MiB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 14790.73
	Virtual memory used (MiB): 8275.77
	Swap memory total (MiB): 6656.00
	Swap memory used (MiB): 486.06
	Space in storage for jna.tmpdir (MiB): available: 90240.64, total: 227341.53
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 90240.64, total: 227341.53
	Space in storage for io.netty.native.workdir (MiB): available: 90240.64, total: 227341.53
	Space in storage for java.io.tmpdir (MiB): available: 90240.64, total: 227341.53
	Space in storage for workdir (MiB): available: 90240.64, total: 227341.53
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		architectury: Architectury 13.0.8
		artifacts: Artifacts 12.0.6
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
			expandability: ExpandAbility 12.0.0
		autofish: XPlus Autofish 1.3.4-fabric-mc1.21.1
		balm-fabric: Balm 21.0.20
			kuma_api: KumaAPI 21.0.5-SNAPSHOT
		better_craftables: Better Craftables 2.0.0
		betterf3: BetterF3 11.0.3
		bettermineshafts: YUNG's Better Mineshafts 1.21.1-Fabric-5.1.1
		c2me: Concurrent Chunk Management Engine 0.3.0+alpha.0.299+1.21.1
			c2me-base: Concurrent Chunk Management Engine (Base) 0.3.0+alpha.0.299+1.21.1
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.3.0+alpha.0.299+1.21.1
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.3.0+alpha.0.299+1.21.1
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.3.0+alpha.0.299+1.21.1
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.3.0+alpha.0.299+1.21.1
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.3.0+alpha.0.299+1.21.1
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-dfc: Concurrent Chunk Management Engine (Optimizations/Density Function Compiler) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.3.0+alpha.0.299+1.21.1
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.3.0+alpha.0.299+1.21.1
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.3.0+alpha.0.299+1.21.1
			c2me-rewrites-chunk-system: Concurrent Chunk Management Engine (Rewrites/Chunk System) 0.3.0+alpha.0.299+1.21.1
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.3.0+alpha.0.299+1.21.1
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.3.0+alpha.0.299+1.21.1
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.3.0+alpha.0.299+1.21.1
			com_ibm_async_asyncutil: asyncutil 0.1.0
			io_reactivex_rxjava3_rxjava: rxjava 3.1.8
			mixinsquared: MixinSquared 0.2.0-beta.6
			net_objecthunter_exp4j: exp4j 0.4.8
			org_jctools_jctools-core: jctools-core 4.0.5
			org_reactivestreams_reactive-streams: reactive-streams 1.0.4
		cicada: CICADA 0.9.1+1.21-1.21.1
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 19.0.0.1
		collective: Collective 7.87
		continuity: Continuity 3.0.0-beta.5+1.21
		cristellib: Cristel Lib 1.2.8
			blue_endless_jankson: jankson 1.2.3
		day_dream: Day Dream 1.0.11
		easyanvils: Easy Anvils 21.1.0
		easymagic: Easy Magic 21.1.0
		echochest: Echo Chest 21.1.0
		enhancedblockentities: Enhanced Block Entities 0.10.2+1.21
		entity_model_features: Entity Model Features 2.2.6
		entity_texture_features: Entity Texture Features 6.2.8
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		expanded_bow_enchanting: Expanded Bow Enchanting 1.1.2
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.11
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.1.1
		fabric-api: Fabric API 0.109.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+da19b51a19
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.23+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
		ferritecore: FerriteCore 7.0.2-hotfix
		forgeconfigapiport: Forge Config API Port 21.1.2
		helditemtooltips: Held Item Tooltips 21.1.0
		horseexpert: Horse Expert 21.1.0
		inventoryprofilesnext: Inventory Profiles Next 2.1.0
		jade: Jade 15.8.3+fabric
		jamlib: JamLib 1.2.2+1.21.1
		java: OpenJDK 64-Bit Server VM 21
		lambdynlights: LambDynamicLights 3.1.3+1.21.1
			pride: Pride Lib 1.2.1+1.21
			spruceui: SpruceUI 5.1.0+1.21
		levelz: LevelZ 2.0.1
		libipn: libIPN 6.2.0
		libz: LibZ 1.0.3
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.15.2
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.15.2
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.15.2
		lightweight-inventory-sorting: Lightweight Inventory Sorting 1.1.2+1.21
		lithium: Lithium 0.14.2-snapshot+mc1.21.1-build.90
		lootr: Lootr 1.21-1.10.33.85
		minecraft: Minecraft 1.21.1
		modernfix: ModernFix 5.19.5+mc1.21.1
		modmenu: Mod Menu 11.0.3
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		mr_mine_treasure: Mine Treasure 1.4.6
		openpartiesandclaims: Open Parties and Claims 0.23.4
		overflowingbars: Overflowing Bars 21.1.1
		patchouli: Patchouli 1.21-87-FABRIC
			fiber: fiber 0.23.0-2
		portable_crafting: Portable Crafting 3.0.3+1.21
			folk_sisby_kaleido-config: kaleido-config 0.3.1+1.3.2
		puzzleslib: Puzzles Lib 21.1.22
		rightclickharvest: Right Click Harvest 4.4.3+1.21.1
		roughlyenoughitems: Roughly Enough Items 16.0.788
			error_notifier: Error Notifier 1.0.11
		showmeyourskin: Show Me Your Skin! 1.11.3+1.21
		shulkerboxtooltip: Shulker Box Tooltip 5.1.2+1.21.1
		shulkerdropstwo: Shulker Drops Two 3.4
		sodium: Sodium 0.6.0+mc1.21.1
		sodium-extra: Sodium Extra 0.6.0+mc1.21.1
		sophisticatedbackpacks: Sophisticated Backpacks 1.21.1-3.20.19.51
			porting_lib_extensions: Porting Lib Extensions 3.1.0+1.21.1
				mm: Manningham Mills 2.3
				porting_lib_accessors: Porting Lib Accessors 3.1.0+1.21.1
				porting_lib_asm: Porting Lib ASM 3.1.0+1.21.1
				porting_lib_attributes: Porting Lib Attributes 3.1.0+1.21.1
				porting_lib_common: Porting Lib Common 3.1.0+1.21.1
			porting_lib_item_abilities: Porting Lib Item Abilities 3.1.0+1.21.1
				porting_lib_blocks: Porting Lib Blocks 3.1.0+1.21.1
				porting_lib_level_events: Porting Lib Level Events 3.1.0+1.21.1
			porting_lib_loot: Porting Lib Loot 3.1.0+1.21.1
				porting_lib_conditions: Porting Lib Conditions 3.1.0+1.21.1
			porting_lib_model_loader: Porting Lib Model Loader 3.1.0+1.21.1
			porting_lib_transfer: Porting Lib Transfer 3.1.0+1.21.1
				porting_lib_core: Porting Lib Core 3.1.0+1.21.1
				porting_lib_gametest: Porting Lib GameTest 3.1.0+1.21.1
			team_reborn_energy: Energy 4.1.0
		sophisticatedcore: Sophisticated Core 1.21.1-0.6.50.61
			mixinextras: MixinExtras 0.5.0-beta.3
			porting_lib_fluids: Porting Lib Fluids 3.1.0+1.21.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 3.1.0+1.21.1
			porting_lib_models: Porting Lib Models 3.1.0+1.21.1
				porting_lib_data: Porting Lib Data 3.1.0+1.21.1
		t_and_t: Towns and Towers 1.13.2
		tiered: Tiered 1.3.5
		tntbreaksbedrock: TNT Breaks Bedrock 3.4
		treeharvester: Tree Harvester 9.1
		trinkets: Trinkets 3.10.0
		villager-pickup: Villager Pickup 1.1.2
		waystones: Waystones 21.1.5
		xaerominimap: Xaero's Minimap 24.6.1
		xaeroworldmap: Xaero's World Map 1.39.0
		yungsapi: YUNG's API 1.21.1-Fabric-5.1.3
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
	Server Running: true
	Player Count: 1 / 8; [class_3222['Hoang_Tiv1107'/3, l='ServerLevel[27/11/24]', x=-126.70, y=19.00, z=364.70]]
	Active Data Packs: vanilla, fabric, artifacts, balm-fabric (incompatible), better_craftables, bettermineshafts (incompatible), collective, easyanvils (incompatible), easymagic (incompatible), echochest (incompatible), fabric-convention-tags-v2, horseexpert (incompatible), levelz, lootr, mr_mine_treasure, openpartiesandclaims (incompatible), patchouli (incompatible), porting_lib_gametest, porting_lib_item_abilities, rightclickharvest, sophisticatedbackpacks (incompatible), sophisticatedcore (incompatible), t_and_t, tiered, trinkets, waystones (incompatible), yungsapi (incompatible), towns_and_towers:resources/t_and_t_waystones_patch
	Available Data Packs: artifacts, balm-fabric (incompatible), better_craftables, bettermineshafts (incompatible), bundle, collective, easyanvils (incompatible), easymagic (incompatible), echochest (incompatible), fabric, fabric-convention-tags-v2, horseexpert (incompatible), levelz, lootr, mr_mine_treasure, openpartiesandclaims (incompatible), patchouli (incompatible), porting_lib_gametest, porting_lib_item_abilities, rightclickharvest, sophisticatedbackpacks (incompatible), sophisticatedcore (incompatible), t_and_t, tiered, towns_and_towers:resources/t_and_t_waystones_patch, trade_rebalance, trinkets, vanilla, waystones (incompatible), yungsapi (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 2536381222188504022
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.16.9-1.21.1

**Comment by BronsonCarder** [comment]
Same, but mine is ticking a piglin. Seems to have completely bricked that save, because it ticks that piglin as soon as it loads and crashes.
It actually said I had "disconnected" from my single player game. lmfao

V1.21.1

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/86c98def0f35e4305ab617f8797ee8d48ad968ac](https://github.com/Globox1997/LevelZ/commit/86c98def0f35e4305ab617f8797ee8d48ad968ac)
