### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by beijuren** [Globox1997/LevelZ#367]
### Minecraft Version

1.21.x

### Mod Loader Version

0.16.9

### Mod Version

levelz-2.0.1+1.21.1

### Describe the Issue

When pillager Marauder uses crossbow, the game crashes

### latest.log

[latest.log](https://github.com/user-attachments/files/17936371/latest.log)

### Do you use any other mods except the required ones?

yes but the mod works fine, apart from this.

**Comment by chrismikh** [comment]
If you have guard villagers mod, its because of it.

**Comment by chrismikh** [comment]
Oh, the 2.0.2 version fixes this
