### ISSUE TITLE
Attributes increase on each world load

### ISSUE THREAD

**Issue by nateify** [Globox1997/LevelZ#378]
### Minecraft Version

1.21.x

### Mod Loader Version

0.16.9

### Mod Version

2.0.2

### Describe the Issue

Issue occurs both in single player and multiplayer with the same set of mods, including the minimal mods in a brand new Prism launcher profile with only LevelZ and dependencies installed.

1. Create a new world
2. Put 5 starter points in defense leading to 3.75 in defense attribute
3. Exit the world
4. Reload the world and press K to open attributes
5. Defense attribute is now at 5.0
6. This repeats indefinitely leading to very inflated attributes - 3rd screenshot shows 6.25 which is going up by 1.25 but further screenshots below show that this inflation is not constant

Screenshots of the above scenario:
![2024-12-29 20_29_15-Minecraft_ 1 21 1 - Singleplayer](https://github.com/user-attachments/assets/f7a48431-1fbd-4e88-a375-886df753fbc4)
![2024-12-29 20_29_35-Minecraft_ 1 21 1 - Singleplayer](https://github.com/user-attachments/assets/da979a1d-7f28-4199-9e18-ecfda4958e75)
![2024-12-29 20_29_55-Minecraft_ 1 21 1 - Singleplayer](https://github.com/user-attachments/assets/63edfda5-3bba-4897-ac30-3916d8819b30)
![image](https://github.com/user-attachments/assets/951d770f-ca84-44fe-9aa2-a00d3cc7f3a9)

Screenshots from another save file before and after which shows that attack, defense, underwater breathing, mining are affected in tandem. Health, movement speed, luck are not. The values that these go up are greater than 1.25 observed above.

Before:
![image](https://github.com/user-attachments/assets/f759dfc3-5d89-40c3-b738-4ad390a11134)

After:
![image](https://github.com/user-attachments/assets/59fad8af-1ca8-4394-ab5f-a5d32fcc3671)

### latest.log

https://mclo.gs/nd5mNTG
https://spark.lucko.me/ETiGceFLt9

### Do you use any other mods except the required ones?

No. It occurs when using only LevelZ and required dependencies

**Comment by Globox1997** [comment]
Please test the latest version, this might fix it.

**Comment by nateify** [comment]
> Please test the latest version, this might fix it.

Thanks, this seems to be fixed!
