### ISSUE TITLE
Smithing Table upgrade progression lock and other suggestions

### ISSUE THREAD

**Issue by FancyMango** [Globox1997/LevelZ#39]
1. By default with the mod you are able to block the ability to craft with specific materials within the brewing stand, it would be a fantastic idea to allow people to level lock specific components within the smithing table.
2. A better way of defining mod specific items to have this level lock within each category, i.e. creating a datapack and setting the "item" parameter to aethermod:valkyriepickaxe for example and adding that to the mining tree; I mention this because I was trying to add a level cap to harpoons from the Alaskanativecraft mod(harpoons are just a derivative of trident) however, the material argument nor specifying the direct item worked.

I've just finished compiling a spreadsheet for the levelling requirements I was going to set up for a server, I'll drop the link here in case it can give you any further ideas, cause I'm really hoping I can get this to work out properly and without hiccups, for now I just have to wait for new updates to come to the mod in the future. https://docs.google.com/spreadsheets/d/1NnZ7dq9CUtjDUmbQBWPc4YXM1_rrTXTIzVw1Kj2LsOk/edit?usp=sharing

**Comment by Globox1997** [comment]
That is a good idea :)
Added smithing restriction with [https://github.com/Globox1997/LevelZ/commit/60140ef2607d8ac042da7ac6969551cefbf9e6cd](https://github.com/Globox1997/LevelZ/commit/60140ef2607d8ac042da7ac6969551cefbf9e6cd)
