### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by kryptongamer** [Globox1997/LevelZ#4]
1. Alchemy its bug. Character lost the points after dead and open a chest or store. https://streamable.com/s3s6fa
2.  K text its bugged, some time text its repeteated 
![image](https://user-images.githubusercontent.com/54698900/130343190-1cf6608c-17dd-4db5-b1a4-f15c96ba8468.png)
3. Decimal number are wrong, some times are large 
![image](https://user-images.githubusercontent.com/54698900/130343212-8bf1ab87-32a5-4dd5-8956-5209b4d52429.png)

**Comment by Globox1997** [comment]
Thanks for the good report :)
Don't understand the first bug, what exactly is wrong there?
Already have a fix for the second bug, just didn't upload it yet :)
Third one will get a fix soon

**Comment by Globox1997** [comment]
Second and third bug is solved with [https://github.com/Globox1997/LevelZ/commit/af7fbbb548eed2d141444b46535305ce3754bdf8](https://github.com/Globox1997/LevelZ/commit/af7fbbb548eed2d141444b46535305ce3754bdf8)

**Comment by kryptongamer** [comment]
1. After you die and open an storage, the character lost the points added on alchemy, look the video

**Comment by Globox1997** [comment]
Ah now I see :D fixed with [https://github.com/Globox1997/LevelZ/commit/8a73289be9e58b31426f1cd2410894843e9c749c](https://github.com/Globox1997/LevelZ/commit/8a73289be9e58b31426f1cd2410894843e9c749c)
