### ISSUE TITLE
Cardboard (Fabric/Spigot) mod Incompatibility (Posted in both the mod's github to make sure it's known)

### ISSUE THREAD

**Issue by Psento** [Globox1997/LevelZ#40]
I'll paste the log, this is with the following mod versions installed:
Cardboard 1.17
Cloth api 2.0.54
Cloth config 5.0.38
fabric api 0.40.8+1.17
fabric language kotlin 1.6.5+kotlin.1.5.31
levelz 1.0.12

[latest.log](https://github.com/Globox1997/LevelZ/files/7335290/latest.log)
![Proof of mods](https://user-images.githubusercontent.com/26581578/137075545-21f4db2d-cd2f-49f4-a1d7-14ad8e146d63.PNG)

**Comment by Globox1997** [comment]
Sadly it doesn't look like cardboard is gonna change the overwrite so I removed the mixin when the mod cardboard is loaded with [https://github.com/Globox1997/LevelZ/commit/24fd4dc1ddb25a5191fd270befb1944f2339848e](https://github.com/Globox1997/LevelZ/commit/24fd4dc1ddb25a5191fd270befb1944f2339848e)
This is not a good solution cause now the player can equip armor items regardless of the level requirement

**Comment by Psento** [comment]
Dope good shit
