### ISSUE TITLE
how to add items to the level requirements

### ISSUE THREAD

**Issue by ironfprcefeild** [Globox1997/LevelZ#43]
The title says it all, i just want to add some items from the mythical ores mod. they don't have it by default and I'm wondering if there is a way to do it by config or data driven?

**Comment by Globox1997** [comment]
readme explains how it works.
With update 1.1.0 datapack creators will be able to lock other mods items/blocks/entities, explained in the readme.
It will come out for mc 1.18

**Comment by Globox1997** [comment]
The example datapack [https://github.com/Globox1997/LevelZ/tree/1.18/exampleDatapack](https://github.com/Globox1997/LevelZ/tree/1.18/exampleDatapack) doesn't show yet how to use custom items but let me know if you need help with that

**Comment by Globox1997** [comment]
Reference #53
