### ISSUE TITLE
Confliction with BetterEnd

### ISSUE THREAD

**Issue by SapphireDragons** [Globox1997/LevelZ#45]
Creation, Equipping, And Removing pieces of armor in betterend cause a server to restart.

"Author of levelZ used it on server
As a result this function doesn't exist and you get crash,

This thing is not hard to fix, it only require additional client side check"

**Comment by Globox1997** [comment]
Don't really get the issue.. What is your fix suggestion exactly?

**Comment by xR4YM0ND** [comment]
If you still have this bug, pls open a new issue.
