### ISSUE TITLE
fire is following me

### ISSUE THREAD

**Issue by olo76** [Globox1997/LevelZ#47]
So im not sure if its this mod, but it happend after i messed with this mod in a modpack, i made all my levels 50, but now fire follows me where ever i go, is this part of the mod or is it a different mod issue?

**Comment by Globox1997** [comment]
Should be the same as with [https://github.com/Globox1997/LevelZ/issues/29](https://github.com/Globox1997/LevelZ/issues/29)
Reopen if still exist with latest levelz + fabric api
