### ISSUE TITLE
Can't really figure out what conflicts with the mod but yea

### ISSUE THREAD

**Issue by GuestTox** [Globox1997/LevelZ#48]
[tl-logger5145313196594297847.txt](https://github.com/Globox1997/LevelZ/files/7446280/tl-logger5145313196594297847.txt)

**Comment by Globox1997** [comment]
Does it happen with levelz only installed?

**Comment by GuestTox** [comment]
> Does it happen with levelz only installed?

it doesn't work the game just crashed + i only put sodium in the mods nothing else except for cloth config and fabric api ofc

**Comment by wolfkidsounds** [comment]
Try changing the fabric version to 0.11.7 - I've had similar issues (server side) with other mods.

**Comment by Globox1997** [comment]
It should be fixed with levelz 1.0.15 and the latest fabric api version, reopen if still exist :)
