### ISSUE TITLE
Crash Without Crash report

### ISSUE THREAD

**Issue by DanMeadWasTaken** [Globox1997/LevelZ#49]
Whenever I add the mod to my pack, it crashes before really starting the game, so no crash report. 

After looking at the Latest.log, i figured out that it was having an issue with Fabric-carpet mod (something to do with exp), so I removed it. Even after that though, there is a new issue, one to do with fishing rods, presumably being caused by go fish mod. no idea though, as it didn't state the mod causing the issue the second time.
The one from after I took carpet mod out, if need be I can send a latest.log for when carpet mod is in as well, and even test taking out other mods to see what all is causing issues
[latest.log](https://github.com/Globox1997/LevelZ/files/7479998/latest.log)

**Comment by Globox1997** [comment]
As issue #26 it is incompatible with the go fish mod.
Would appreciate the carpet crash log

**Comment by DanMeadWasTaken** [comment]
Here is the one for the conflict with Fabric-Carpet mod (if you don't know, despite the name, it doesn't add carpets)
[latest.log](https://github.com/Globox1997/LevelZ/files/7485881/latest.log)
As for go fish, I'll see about sending them a message if no one else has yet. As well as see if any other mods in my pack are having conflicts. 

If it turns out there's nothing you can do on your end for carpet, I'd be much appreciated to know if there's another mod i could use to add 3x3&5x5 mining to modded items, or making it so that villagers can harvest stuff such as nether wart

**Comment by Globox1997** [comment]
Fixed compat with carpets with [https://github.com/Globox1997/LevelZ/commit/3d56ffdee5fb4c7a0262218c4c1da06fab7d953a](https://github.com/Globox1997/LevelZ/commit/3d56ffdee5fb4c7a0262218c4c1da06fab7d953a)
The downside is, player can abuse death experience to level up their skills
