### ISSUE TITLE
0 stats

### ISSUE THREAD

**Issue by kryptongamer** [Globox1997/LevelZ#5]
Character back to 0 stats after pass for a portal Overworld -> nether per example

https://streamable.com/u66chv

**Comment by Globox1997** [comment]
[levelz-1.0.4.zip](https://github.com/Globox1997/LevelZ/files/7031004/levelz-1.0.4.zip)
could you test this for me? check also the xp bar and you have to unzip the file

**Comment by kryptongamer** [comment]
ok its working only changing in the server

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/51b96638e33eee1ba034bfbc34daf37879e4bf53](https://github.com/Globox1997/LevelZ/commit/51b96638e33eee1ba034bfbc34daf37879e4bf53)

**Comment by kryptongamer** [comment]
not working sorry

https://clips.twitch.tv/ClumsyRelievedYakFreakinStinkin-lQ3pcHCN29LK0peG

**Comment by Globox1997** [comment]
Now fixed with [https://github.com/Globox1997/LevelZ/commit/d60fc28ef358d55391b09dc618e4440963022a15](https://github.com/Globox1997/LevelZ/commit/d60fc28ef358d55391b09dc618e4440963022a15)

**Comment by kiddthejuice** [comment]
I figured I would post in here vs making a new post, but my modded 1.17.1 server players are experiencing this issue. It doesn't happen every time they go through the portals but it has been happening when they go into the Nether. They haven't reported this issue when using the Waystones mod I have on the server, just when using the vanilla portals. I do have Better Nether on the server. I currently have Vers. 1.0.15 of this mod uploaded on the server.

**Comment by Globox1997** [comment]
Might be a mod incompatibility? @kiddthejuice
