### ISSUE TITLE
Datapack - Mods

### ISSUE THREAD

**Issue by lowenplay** [Globox1997/LevelZ#50]
Hi, i'm trying to add requirement to items from other mods. I edited the vanilla items perfectly, but I couldn't for mod items.

I am trying this:

/item/test.json

{
     "replace": true,
     "skill": "alchemy",
     "level": 10,
     "item": "artifacts: crystal_heart"
}

Also add tags just in case:

/ tags / items /

{
     "replace": true
     "values": [
         "artifacts: crystal_heart"
     ]
}

What am I doing wrong? (I'm newbie, sorry)

Mods: Artifacts, SurvivalPlus, ....

Thanks

**Comment by Globox1997** [comment]
With update 1.1.0 datapack creators will be able to lock other mods items/blocks/entities, explained in the readme.
It will come out for mc 1.18
"replace" has only be true if you want to overwrite an existing file for the same item :)

**Comment by Globox1997** [comment]
For reference #43
