### ISSUE TITLE
Alchemy broke: Instant damage effect + fire around me

### ISSUE THREAD

**Issue by CynonMCC** [Globox1997/LevelZ#54]
If i put some level on alchemy, i get randomly instant damage and my environment catch randomly fire around me. Please fix this.

**Comment by Globox1997** [comment]
Does this happen when LevelZ is only installed and do you use the latest version?

**Comment by CynonMCC** [comment]
I use the mod in a Modpack with this CurseForge Launcher:
![Screenshot 2021-11-15 162712](https://user-images.githubusercontent.com/19671952/141809630-a4f8f9ec-46fb-4008-b0d0-1308acac05a4.png)
This is the Modpack:
![Screenshot 2021-11-15 162751](https://user-images.githubusercontent.com/19671952/141809633-f659a6a8-079f-4ce5-9682-97a5bea9ca56.png)
![Screenshot 2021-11-15 162817](https://user-images.githubusercontent.com/19671952/141809635-ed762012-3f5a-44ae-a2fa-bed01a8e345f.png)
The mods are launched with this version of Fabric:
![Screenshot 2021-11-15 162911](https://user-images.githubusercontent.com/19671952/141809647-d7c5d86d-d7f3-4135-8d4e-265b6c644617.png)

Here is a list of all the used mods:
[mods.txt](https://github.com/Globox1997/LevelZ/files/7539756/mods.txt)
alternative links:
https://docs.google.com/document/d/e/2PACX-1vQ3zLMkiwhuwHSdfkSqtYbCCPjJbhOOaA8LywX-fvir1u83ka-X4Xir5cayObNhQBkfHY-DlXt6tcWp/pub
or
https://www.curseforge.com/minecraft/modpacks/pwrdown-rpg-fabric

This is the version of LevelZ which i use:
![2021-11-15_16 39 24](https://user-images.githubusercontent.com/19671952/141810281-d8935fcf-2c67-4b4a-a595-3fea141e4768.png)

**Comment by Globox1997** [comment]
Very well supplied information, thanks.
The simple solution is, update levelz to the latest version (1.0.15), cause if I remember correctly this is a incompatibility with another mod, fixed in a later version.

**Comment by Globox1997** [comment]
Should be the same as [https://github.com/Globox1997/LevelZ/issues/29](https://github.com/Globox1997/LevelZ/issues/29)
