### ISSUE TITLE
[suggestion] run command when level

### ISSUE THREAD

**Issue by Monster-Zer0** [Globox1997/LevelZ#55]
basically

if alchemy level 10

run `/give @s potion`

also a description so it can show in the levelz menu.

something like that.

this could be useful in conjunction with game phases when it gets updated.

one could have a certain level reach.. then run` /phase grant @s one`

maybe optional message to the player as well.

**Comment by Globox1997** [comment]
Added an advancement trigger with [https://github.com/Globox1997/LevelZ/commit/acd36dd5a6c9a0aa1d2c2b71979c0e44ec0ed203](https://github.com/Globox1997/LevelZ/commit/acd36dd5a6c9a0aa1d2c2b71979c0e44ec0ed203)
You can look here how to run a command on specific levels [https://github.com/Globox1997/LevelZ/blob/1.18/src/main/resources/data/levelz/advancements/reach_levelz_100.json](https://github.com/Globox1997/LevelZ/blob/1.18/src/main/resources/data/levelz/advancements/reach_levelz_100.json)
Here is a function [https://github.com/Globox1997/LevelZ/blob/1.18/src/main/resources/data/levelz/functions/level100.mcfunction](https://github.com/Globox1997/LevelZ/blob/1.18/src/main/resources/data/levelz/functions/level100.mcfunction)
