### ISSUE TITLE
Alchemy Kills

### ISSUE THREAD

**Issue by LoremasterTeach** [Globox1997/LevelZ#56]
so after some experimentation with Levelz. learning alchemy at any level will start to kill you keeping you at or below half hp regardless of how many hearts you have. I have screwed around with a combination of levels in health and alchemy and the results are the same.

**Comment by Globox1997** [comment]
instantly closed?

**Comment by LoremasterTeach** [comment]
Yes i realized the issue had alread ybeen addressed and corrected
