### ISSUE TITLE
Interactive icons

### ISSUE THREAD

**Issue by Renkane** [Globox1997/LevelZ#58]
When you click any skill icon on levelz-1.1.0. ver the game crashes presenting the following error:
"
The game crashed whilst mousereleased event handler
Error: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
Exit Code: -1
"

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/LevelZ/commit/6c97acf32390ba765e802999bf07767112100c69](https://github.com/Globox1997/LevelZ/commit/6c97acf32390ba765e802999bf07767112100c69)

**Comment by Renkane** [comment]
Thanks for the fast fix, loving this mod.
