### ISSUE TITLE
Elytras

### ISSUE THREAD

**Issue by kryptongamer** [Globox1997/LevelZ#6]
I can use elytes with level 0 of agility. Maybe is the mod trinkets https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric . Its possible an adaptation?

**Comment by Globox1997** [comment]
For whatever reason, in prod env the mod can't find the refmap so I can't mix into the trinkets api code.
Will leave it open and try it at another time

**Comment by Globox1997** [comment]
Added trinkets compat, reference #75
