### ISSUE TITLE
Levelz and Origins

### ISSUE THREAD

**Issue by Zophix** [Globox1997/LevelZ#68]
I'm running Levelz, Origins and Origins Classes. Whenever I create a world I get this error and the game crashes. I've read comments of people saying these mods work together but it's not happening for me.

[crash-2021-12-14_19.41.51-client.txt](https://github.com/Globox1997/LevelZ/files/7715855/crash-2021-12-14_19.41.51-client.txt)

**Comment by Zophix** [comment]
Yeah for some reason Origins/Origins Classes and LevelZ are not compatible but they will work if you run AdventureZ.

**Comment by Globox1997** [comment]
Reference #59
