### ISSUE TITLE
Xp bug

### ISSUE THREAD

**Issue by kryptongamer** [Globox1997/LevelZ#7]
Level max not working. Players can pass over level max

**Comment by Globox1997** [comment]
This shouldn't be possible, are the buttons still click able when player reaches the max lvl of the specific skill?

**Comment by kryptongamer** [comment]
No, but general level can pass the levelmax and experience bug some times 
![image](https://user-images.githubusercontent.com/54698900/130436626-a258369a-fff8-4ca3-8525-18528a71499b.png)

**Comment by Globox1997** [comment]
Fixed max lvl with [https://github.com/Globox1997/LevelZ/commit/c307e4a7abeffceb0b43c9ef7b2d0781809fe89f](https://github.com/Globox1997/LevelZ/commit/c307e4a7abeffceb0b43c9ef7b2d0781809fe89f)

**Comment by Globox1997** [comment]
When does the experience bug happen exactly? I need to reproduce it to fix it

**Comment by kryptongamer** [comment]
I could not say, I have not realized when it happened to me, but several users have the exp bug the same as me at different levels

**Comment by Globox1997** [comment]
If you know when it happens, let me know.
As long as it occurs, this issue will stay open

**Comment by kryptongamer** [comment]
Its a visual bug, they can up more but exp its negative

**Comment by Globox1997** [comment]
yea but when does it exactly happen? Looks like it only happens on the server.

**Comment by Cliferz** [comment]
it happens when using Dark Enchanter from Dark Enchanting Mod for me (single player).

**Comment by kryptongamer** [comment]
True, i can confirm, enchants on dark enchanter sustract exp to LevelProgress

**Comment by Globox1997** [comment]
Pushing this to another issue here [https://github.com/Globox1997/LevelZ/issues/17](https://github.com/Globox1997/LevelZ/issues/17)
