### ISSUE TITLE
Dying grants you additional levels

### ISSUE THREAD

**Issue by reeceparry** [Globox1997/LevelZ#70]
It seems that dying and picking up your gravestone grants you x amount of XP you had upon death - this stacks with your Levelz level & XP and appears to be a cheap way to level up and progress. Please fix!

**Comment by Vaelzan** [comment]
Last time I looked into this it was the Clumps mod causing that to break, but I also wouldn't be surprised if certain gravestone mods do the same thing. You don't get LevelZ XP by picking up the experience orbs from your death location without those mods.

Edit: Relevant issue here: https://github.com/Globox1997/LevelZ/issues/44

**Comment by viperp12** [comment]
I removed all other mods and it still does this. I delved into researching how to either stop xp loss, or somehow stop the xp gain for the levelz mod after collecting your items, but unfortunately I am not seeing an easy solution here. Probably will require somehow tagging the xp orbs so it is known that they are coming from a corpse.

**Comment by Globox1997** [comment]
As a reference #51

**Comment by Globox1997** [comment]
Should be fixed with at least the latest update for 1.18.2 since levelz uses a new xp system
