### ISSUE TITLE
Using silk touch with a high mining skill gives you bonus ore blocks, which you can then place down again and get more ore.

### ISSUE THREAD

**Issue by AnthonyChester3D** [Globox1997/LevelZ#71]
A player on my server (Running Valhelsia: Enhanced Vanilla 1.0) is able to dupe items by placing a stack of nether quartz ore, then silk touching it.  He collected a stack of 64 ore, then placed them to silk touch them again, and got 12 free blocks at level 16 mining (with level 6 luck if that matters)

Expected Behavior: One block drops when using silk touch.

Actual Behavior: Sometimes two blocks drop when using silk touch.

Impact: This causes players to no longer need to go mining as long as they hoard ore blocks. 

Notes: Bonus items should still drop when using other enchants, but with silk touch it creates potential for endless item duping at the cost of silk touch durability.  

We're using version 1.1.1 of levelz if that helps. (It's what's included in the modpack.)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/LevelZ/commit/94f284fd6a1ccb0fae1a014f9540bc48159fce63](https://github.com/Globox1997/LevelZ/commit/94f284fd6a1ccb0fae1a014f9540bc48159fce63)
Thanks for reporting
