### ISSUE TITLE
Adding restrictions to trinkets?

### ISSUE THREAD

**Issue by genki-angel** [Globox1997/LevelZ#75]
I tried making a datapack for a modded item which goes into the trinket slot. It registers and shows that it has worked but it is still equip-able by directly putting it in the slot or by shift right clicking it. However using it by the hotbar does work correctly and prompts the required level pop up.

`{
    "replace": true,
    "skill": "agility",
    "level": 18,
    "item": "minecraft:custom_item",
    "object": "icarus:white_feathered_wings"
}`

**Comment by MarkNoName** [comment]
Having the same issue here with a mod called "Things" which also takes the items and puts them into the trinkets slots. Would be nice if this issue/feature gets fixed/added in a future update :)

**Comment by Globox1997** [comment]
Added trinkets compatibility with [https://github.com/Globox1997/LevelZ/commit/a1726f57a1d24db25068b9a80b325ded80deac05](https://github.com/Globox1997/LevelZ/commit/a1726f57a1d24db25068b9a80b325ded80deac05)
You have to use the custom item list to restrict items
