### ISSUE TITLE
LevelZ and Dark Enchanting problem

### ISSUE THREAD

**Issue by xillenburg** [Globox1997/LevelZ#76]
![2021-12-20_12 02 28](https://user-images.githubusercontent.com/92593235/146710152-6da6bdb6-62a4-4e28-84cb-29ad8efb88a5.png)

whenever I enchant with high-cost enchantments that exceed the XP in LevelZ using the dark enchantment table, my levelZ xp goes down to a negative value.

**Comment by Globox1997** [comment]
As reference #17
