### ISSUE TITLE
[1.18.1]LevelZ incompatible with Modern Industrialization v1.0.0

### ISSUE THREAD

**Issue by thecow275** [Globox1997/LevelZ#77]
Was told by the MI developer to post my log here due to incompatibility on your side causing crashes when using their ingame manual or trying to craft their Steam Minign Drill.

log:https://paste.ee/p/1yn8h

**Comment by xR4YM0ND** [comment]
Same for me -> Rendering Crash when opening the Getting Started Page 

Fabric  1.18.1
Modpack: [The Progressor](https://www.curseforge.com/minecraft/modpacks/the-progressor)
Log: [Latest.log](https://gist.github.com/SpigotDE/0369b0f0741cc8e61593c65e59fc2ed9)
Modern Industrialization Issue [#229](https://github.com/AztechMC/Modern-Industrialization/issues/229)

**Comment by Globox1997** [comment]
Pls update to the latest mod version

**Comment by AgrippaDaRippa** [comment]
> Pls update to the latest mod version

 Even after updating to 1.1.5,  I still experience the same crash.

**Comment by Globox1997** [comment]
Should be fixed with 1.1.6, reopen if still happening
