### ISSUE TITLE
not working sorry

### ISSUE THREAD

**Issue by kryptongamer** [Globox1997/LevelZ#8]
not working sorry

https://clips.twitch.tv/ClumsyRelievedYakFreakinStinkin-lQ3pcHCN29LK0peG

_Originally posted by @kryptongamer in https://github.com/Globox1997/LevelZ/issues/5#issuecomment-903648636_

**Comment by Globox1997** [comment]
Reopen old issues instead of opening new ones :) [https://github.com/Globox1997/LevelZ/issues/5](https://github.com/Globox1997/LevelZ/issues/5)
