### ISSUE TITLE
Suggestion/QoL/user friendly: Show level in inventory, add link from inventory to HUB

### ISSUE THREAD

**Issue by SattesKrokodil** [Globox1997/LevelZ#83]
![image](https://user-images.githubusercontent.com/20082712/147929181-f12b25ee-7abd-469b-b60f-e22a31c07abe.png)

I hope you are doing well Globox! (= Finally got the time/mental to test and give feedback.

**Comment by Globox1997** [comment]
Hey Sattes, great to hear from you :D
Hope you had a good time with your friends/family during these christmas and new years days :)
Both options look cool, if one of those get added, removing the existing keybind would be good?
Which version do you prefer? 
For version 1, I could add a hover state which enlarges the small thing and say "skill tree" or something, or it could be a symbol or something.

**Comment by SattesKrokodil** [comment]
I wouldn't remove the hotkey people can do that on their own if they don't
want that. I just loaded the mod and the first thing was that I had to
check what hotkey it is, if you play a modpack and you don't know that the
mod is in there it could be problematic for players. I think the best
solution is a hover button next to the craftingbook icon, if you hover it
it could say "stats (default key 'K')". Personally I'll use the hotkey but
yeah new player experience :)

Bonus points if you make it change the button sprite when the player has
unspent level points!

Another thing you could potentially add, if the player levels up maybe a
sound and some particles? Nothing fancy just one burst of golden dust
particles or something (if you want I can assist there)

I hope you are having a nice time, and sorry in advance I'll probably write
some more things haha

Globox_Z ***@***.***> schrieb am Mo., 3. Jän. 2022, 14:23:

**Comment by SattesKrokodil** [comment]
I wouldn't remove the hotkey people can do that on their own if they don't
want that. I just loaded the mod and the first thing was that I had to
check what hotkey it is, if you play a modpack and you don't know that the
mod is in there it could be problematic for players. I think the best
solution is a hover button next to the craftingbook icon, if you hover it
it could say "stats (default key 'K')". Personally I'll use the hotkey but
yeah new player experience :)

Bonus points if you make it change the button sprite change 
when the player has
unspent level points!

Another thing you could potentially add, if the player levels up maybe a
sound and some particles? Nothing fancy just one burst of golden dust
particles or something (if you want I can assist there)

I hope you are having a nice time, and sorry in advance I'll probably write
some more things haha

Edit: nvm I think left side with hover and expand would be awesome!

Edit2: if you lack time, I can make the buttons/hover thingy if you want, fitting the theme of the mod - got time and energy :]

**Comment by Globox1997** [comment]
Yea that could be problematic and solved with your idea. 
I still like both approaches so you can decide what you like more, what kind of symbol do you think fits best?
The sound idea is good, there is already something like that but not really used (only if reached a level divisible by 5)

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/LevelZ/commit/0d50bb3f192d4d8795c539160a80c9c3c332f78b](https://github.com/Globox1997/LevelZ/commit/0d50bb3f192d4d8795c539160a80c9c3c332f78b)
