### ISSUE TITLE
LevelZ on server uses local config

### ISSUE THREAD

**Issue by DiegoRutolo** [Globox1997/LevelZ#84]
When playing on a server, it uses the config in the client, instead of the server.

We could only test with `xpBaseCost`, when we tried to adjust it for everyone.

**Comment by Globox1997** [comment]
mh server settings should overwrite client settings

**Comment by camlyall** [comment]
Having the same issue here. Players on server are able to adjust their own config settings

**Comment by Globox1997** [comment]
This is fixed with the latest update
