### ISSUE TITLE
Modded items don't show the "locked" entry when you hover them, which makes it impossible to use the datapack system :/

### ISSUE THREAD

**Issue by SattesKrokodil** [Globox1997/LevelZ#85]
![image](https://user-images.githubusercontent.com/20082712/148042007-347340a8-9c87-4971-a631-c65247a94643.png)

-> 

![image](https://user-images.githubusercontent.com/20082712/148042099-5c757721-a96d-473c-bd6c-a3783d6216ea.png)

Is it possible to get a "fix" for that?

**Comment by Globox1997** [comment]
Did you use the custom item restriction? Or the material restriction?

**Comment by Globox1997** [comment]
Since at least the latest version, custom restrictions will solve the issue if the material string can't get read correctly for restriction.
This happens when the item material isn't saved inside an enum which adds a random addition to the material string.
