### ISSUE TITLE
Adding Piglin Bartering to Trade (enhancement)

### ISSUE THREAD

**Issue by unweeked** [Globox1997/LevelZ#86]
It's self explanatory: Piglin "Trading" should be under "Trade". It could be available at lvl 15 for example.

**Comment by Globox1997** [comment]
Good idea, added with [https://github.com/Globox1997/LevelZ/commit/580dc359dc9fc78f03d2bc98c97642ce14f0178a](https://github.com/Globox1997/LevelZ/commit/580dc359dc9fc78f03d2bc98c97642ce14f0178a)
