### ISSUE TITLE
Game crash when using the enchanting table (log and possible problem location)

### ISSUE THREAD

**Issue by SattesKrokodil** [Globox1997/LevelZ#87]
crashlog: https://pastebin.com/5eHfdzDe

Dafuqs pointed out that the issue is caused by this part if it helps (=

https://github.com/Globox1997/LevelZ/blob/d22a14c0aca37fed4f87a09ce926af5b87508d59/src/main/java/net/levelz/mixin/misc/EnchantmentScreenHandlerMixin.java

**Comment by Globox1997** [comment]
The crash log you attached came to an incompat with backslot which is fixed in backslot version 1.2.4, can you attach the real crash log pls

**Comment by SattesKrokodil** [comment]
done, sorry had an old one open too and copy pasted the wrong one

**Comment by Globox1997** [comment]
Fixed enchanting table issue with [https://github.com/Globox1997/LevelZ/commit/1e3dbb9f0d48b04e786f7988ba2fb64270e1e175](https://github.com/Globox1997/LevelZ/commit/1e3dbb9f0d48b04e786f7988ba2fb64270e1e175)
