### ISSUE TITLE
[1.18.1] Sword restriction is broken

### ISSUE THREAD

**Issue by MarkNoName** [Globox1997/LevelZ#89]
Stone Tools: Can't even craft a single tool. Pickaxe, Axe, Shovel are not usable when trying to mine. Sword is making damage
Above Stone Tools: I can craft every single tool. Pickaxe, Axe, Shovel are not usable when trying to mine. Armor is also not usable. Sword is making damage.

**Comment by MarkNoName** [comment]
Uploading Minecraft 2022.01.09 - 17.36.36.10.DVR.mp4…

using no datapacks with default config file

**Comment by MarkNoName** [comment]
https://user-images.githubusercontent.com/35975662/148691656-b66814fd-0e57-4f09-8f84-7b57391e7ea1.mp4

using no datapacks with default config file

**Comment by Globox1997** [comment]
Yes it is broken, reference #79
