### ISSUE TITLE
[Suggestion] Expand the /playerstats command to be able to get/set/add/subtract as options.

### ISSUE THREAD

**Issue by Vaelzan** [Globox1997/LevelZ#90]
Currently the `/playerstats` command can only set the value of skills/points/levels/progress, but there are some situations where it could be useful to be able to get the current value, and/or to add/subtract a value.

In my case my intention is to award some extra points to certain skills upon the player obtaining certain advancements. I'm able to use a custom script in KubeJS to do most of this (since it has a built-in advancement event and it can run commands with escalated permissions), but without a way to either check the current value of a skill or to add points (rather than setting them) I'm unable to add skill points to a player.

I imagine that this functionality would also be useful for server admins who may want to check a player's stats, or for map makers using command blocks.

**Comment by Globox1997** [comment]
Since commands are executables, you can't use them to get a value.
I will add a "add", "remove" and "set" addition to the command, that should work for all your needs :)

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/LevelZ/commit/40cb989bc6eb5854073dfff34111afc927b428b5](https://github.com/Globox1997/LevelZ/commit/40cb989bc6eb5854073dfff34111afc927b428b5)

**Comment by Vaelzan** [comment]
Thanks.

I should probably have been clearer about what I was thinking of with `get` though, which was to have it return the value in chat, similar to how feedback from other commands works (eg. using `/fill` in vanilla Minecraft returns the number of blocks filled as a chat message).

**Comment by Globox1997** [comment]
Ah okay, added a print command with [https://github.com/Globox1997/LevelZ/commit/3c24c8de3596eaa18ea7ffba83b686309bf642f7](https://github.com/Globox1997/LevelZ/commit/3c24c8de3596eaa18ea7ffba83b686309bf642f7)
