### ISSUE TITLE
[Suggestion] Recipe Locking

### ISSUE THREAD

**Issue by Miku0Sama** [Globox1997/LevelZ#91]
Datapacks along with kubeJS have the ability to manipulate and even remove recipes. Is it possible then, for recipes to be locked behind certain levels? I know this was something that had been done by other mods in the past (the names of which escape me) but I wasn't sure if it's something that could A) already be done using kubeJS with your mod or B) something that could be added using Fabric's API

**Comment by Globox1997** [comment]
I have no idea if kubeJS supports something like that, never used it.
There might be people who know this

**Comment by Globox1997** [comment]
Ah wait since v1.3.0 you can restrict recipes with levels.
[https://github.com/Globox1997/LevelZ#7-crafting-since-version-130](https://github.com/Globox1997/LevelZ#7-crafting-since-version-130)
