### ISSUE TITLE
[Suggestion] Rare candy like skill points as rare drop from mobs

### ISSUE THREAD

**Issue by Dinodug** [Globox1997/LevelZ#94]
To add a little extra immersion to the mod as well as encouraging leveling up by killing things. 
I know quite a few people who go that route, and I think it would be good to encourage them to embrace their method of using your mod. :)

Perhaps the item could have a right-click ability so that way you could give it to someone, or maybe even sell it if you don't need it?
Another benefit is that this would add passive compatibility with better questing or other questing mods, because the drop could be used as a quest reward as well.

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/LevelZ/commit/e177c8e9369c4743ebd1e3fa613fcd96bd330a3b](https://github.com/Globox1997/LevelZ/commit/e177c8e9369c4743ebd1e3fa613fcd96bd330a3b)
Was a great idea thanks :)
