### ISSUE TITLE
Level progress is not kept after dying with keepInventory : true

### ISSUE THREAD

**Issue by unweeked** [Globox1997/LevelZ#98]
^

**Comment by JakeSublime** [comment]
If im not mistaken, make sure in the mod config, drop experience is set to false. I believe this makes sure you do not lose your mod experience/levels on death. 

This can cause a small issue, however, when going to your dead body and picking up dropped xp, as the mod will interpret this xp as new xp.

**Comment by Globox1997** [comment]
turn the config setting "resetCurrentXP" to false :)
death experience will only cause issues if you have a mod installed, which modifies experience like the mod "clump"

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/LevelZ/commit/2fc1e96913c48d612039a753e948daf3dc42a38f](https://github.com/Globox1997/LevelZ/commit/2fc1e96913c48d612039a753e948daf3dc42a38f)
