### ISSUE TITLE
Cannot add some mod items to LevelZ progression

### ISSUE THREAD

**Issue by JakeSublime** [Globox1997/LevelZ#99]
Im trying to add copper armor from the mod "Copper Armor & Tools", but cant get the armor to lock behind defense lv 6. 

I can get the tools to restrict normally, but not the armor. Im using the same method, IE: 

`{
    "replace": false,
    "skill": "defense",
    "level": 6,
    "item": "minecraft:custom_item",
    "object": "copperarmorandtools:copperchestplate"
}`

The above does not work. However, the below works for tools: 

`{
    "replace": false,
    "skill": "mining",
    "level": 6,
    "item": "minecraft:custom_item",
    "object": "copperarmorandtools:copperpickaxe"
}`

And the spelling is correct afaict: 
![image](https://user-images.githubusercontent.com/43627636/150666385-6355970c-8c8e-4ffd-8e4e-c3f3edd07cc9.png)

EDIT:

It seems other mods are being fishy as well. Vanilla Hammers and Vanilla Excavators, both by the same mod author, the excavators i can control the level as normal. The hammers, i cannot control. And, interestingly enough, you can see here that your mod IS seeing the changes im making in my datapack, but it is not applying them to the items:

![image](https://user-images.githubusercontent.com/43627636/150701970-513d393a-d5d8-4c97-a7fa-afada3e1d8a5.png)

![image](https://user-images.githubusercontent.com/43627636/150701996-67ab9b08-255f-487c-805f-8515bf15e0ac.png)

![image](https://user-images.githubusercontent.com/43627636/150702010-eb542570-d2b6-4ab8-b73b-bf184566c49f.png)

**Comment by josef-dijon** [comment]
I've seen the same things with Advanced Netherite armors and Vanilla Hammers.

**Comment by Globox1997** [comment]
I guess you read the item section of the github readme and I recommend to use item materials instead of the custom item restriction.

**Comment by josef-dijon** [comment]
At least for Vanilla Hammers, the problem with using the material definition instead is that hammers don't count as a "Minecraft:tool" and so no restrictions are applied. Same with Advanced Netherite, a netherite_diamond_helmet doesn't count as "Minecraft:armor".

**Comment by Jurklein** [comment]
Did you try setting "replace" to true?

**Comment by Globox1997** [comment]
I refer my discord which can be found on the curseforge website for questions about datapacks for levelz
